/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as LegalesArrepentimientoRouteImport } from './routes/legales.arrepentimiento'
import { Route as LegalesComisionesRouteImport } from './routes/legales.comisiones'
import { Route as LegalesPrivacidadRouteImport } from './routes/legales.privacidad'
import { Route as LegalesTerminosRouteImport } from './routes/legales.terminos'
import { Route as AdminAdministracionUsuariosRouteImport } from './routes/admin.administracion.usuarios'
import { Route as AdminConfiguracionIndexRouteImport } from './routes/admin.configuracion.index'
import { Route as AdminEstadisticasDepositosRetirosRouteImport } from './routes/admin.estadisticas.depositos-retiros'
import { Route as AdminEstadisticasIndicadoresRouteImport } from './routes/admin.estadisticas.indicadores'
import { Route as AdminGeneralMovimientosRouteImport } from './routes/admin.general.movimientos'
import { Route as AdminGeneralUsuariosRouteImport } from './routes/admin.general.usuarios'
import { Route as AdminOtcTasasRouteImport } from './routes/admin.otc.tasas'
import { Route as AdminPagosAprobacionRouteImport } from './routes/admin.pagos.aprobacion'
import { Route as AdminPagosMetodosRouteImport } from './routes/admin.pagos.metodos'
import { Route as AdminVerificacionIdentidadRouteImport } from './routes/admin.verificacion.identidad'
import { Route as AdminVerificacionListasRouteImport } from './routes/admin.verificacion.listas'
import { Route as AdminAdministracionUsuariosIndexRouteImport } from './routes/admin.administracion.usuarios.index'
import { Route as AdminAdministracionUsuariosOperadoresRouteImport } from './routes/admin.administracion.usuarios.operadores'
import { Route as AdminAdministracionUsuariosRolesRouteImport } from './routes/admin.administracion.usuarios.roles'
import { Route as AdminGeneralMovimientosIndexRouteImport } from './routes/admin.general.movimientos.index'
import { Route as AdminGeneralMovimientosComisionesRouteImport } from './routes/admin.general.movimientos.comisiones'
import { Route as AdminGeneralMovimientosDepositosRouteImport } from './routes/admin.general.movimientos.depositos'
import { Route as AdminGeneralMovimientosRetirosRouteImport } from './routes/admin.general.movimientos.retiros'
import { Route as AdminGeneralUsuariosIndexRouteImport } from './routes/admin.general.usuarios.index'
import { Route as AdminOtcRegistroIndexRouteImport } from './routes/admin.otc.registro.index'
import { Route as AdminVerificacionClientesIndexRouteImport } from './routes/admin.verificacion.clientes.index'
import { Route as AdminVerificacionKybIndexRouteImport } from './routes/admin.verificacion.kyb.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const LegalesArrepentimientoRoute = LegalesArrepentimientoRouteImport.update({
  id: '/legales/arrepentimiento',
  path: '/legales/arrepentimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalesComisionesRoute = LegalesComisionesRouteImport.update({
  id: '/legales/comisiones',
  path: '/legales/comisiones',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalesPrivacidadRoute = LegalesPrivacidadRouteImport.update({
  id: '/legales/privacidad',
  path: '/legales/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalesTerminosRoute = LegalesTerminosRouteImport.update({
  id: '/legales/terminos',
  path: '/legales/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdministracionUsuariosRoute =
  AdminAdministracionUsuariosRouteImport.update({
    id: '/administracion/usuarios',
    path: '/administracion/usuarios',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConfiguracionIndexRoute = AdminConfiguracionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminConfiguracionRoute,
} as any)
const AdminEstadisticasDepositosRetirosRoute =
  AdminEstadisticasDepositosRetirosRouteImport.update({
    id: '/estadisticas/depositos-retiros',
    path: '/estadisticas/depositos-retiros',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEstadisticasIndicadoresRoute =
  AdminEstadisticasIndicadoresRouteImport.update({
    id: '/estadisticas/indicadores',
    path: '/estadisticas/indicadores',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminGeneralMovimientosRoute = AdminGeneralMovimientosRouteImport.update({
  id: '/general/movimientos',
  path: '/general/movimientos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeneralUsuariosRoute = AdminGeneralUsuariosRouteImport.update({
  id: '/general/usuarios',
  path: '/general/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOtcTasasRoute = AdminOtcTasasRouteImport.update({
  id: '/otc/tasas',
  path: '/otc/tasas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagosAprobacionRoute = AdminPagosAprobacionRouteImport.update({
  id: '/pagos/aprobacion',
  path: '/pagos/aprobacion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagosMetodosRoute = AdminPagosMetodosRouteImport.update({
  id: '/pagos/metodos',
  path: '/pagos/metodos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificacionIdentidadRoute =
  AdminVerificacionIdentidadRouteImport.update({
    id: '/verificacion/identidad',
    path: '/verificacion/identidad',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminVerificacionListasRoute = AdminVerificacionListasRouteImport.update({
  id: '/verificacion/listas',
  path: '/verificacion/listas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministracionUsuariosIndexRoute =
  AdminAdministracionUsuariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdministracionUsuariosRoute,
  } as any)
const AdminAdministracionUsuariosOperadoresRoute =
  AdminAdministracionUsuariosOperadoresRouteImport.update({
    id: '/operadores',
    path: '/operadores',
    getParentRoute: () => AdminAdministracionUsuariosRoute,
  } as any)
const AdminAdministracionUsuariosRolesRoute =
  AdminAdministracionUsuariosRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AdminAdministracionUsuariosRoute,
  } as any)
const AdminGeneralMovimientosIndexRoute =
  AdminGeneralMovimientosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminGeneralMovimientosRoute,
  } as any)
const AdminGeneralMovimientosComisionesRoute =
  AdminGeneralMovimientosComisionesRouteImport.update({
    id: '/comisiones',
    path: '/comisiones',
    getParentRoute: () => AdminGeneralMovimientosRoute,
  } as any)
const AdminGeneralMovimientosDepositosRoute =
  AdminGeneralMovimientosDepositosRouteImport.update({
    id: '/depositos',
    path: '/depositos',
    getParentRoute: () => AdminGeneralMovimientosRoute,
  } as any)
const AdminGeneralMovimientosRetirosRoute =
  AdminGeneralMovimientosRetirosRouteImport.update({
    id: '/retiros',
    path: '/retiros',
    getParentRoute: () => AdminGeneralMovimientosRoute,
  } as any)
const AdminGeneralUsuariosIndexRoute =
  AdminGeneralUsuariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminGeneralUsuariosRoute,
  } as any)
const AdminOtcRegistroIndexRoute = AdminOtcRegistroIndexRouteImport.update({
  id: '/otc/registro/',
  path: '/otc/registro/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificacionClientesIndexRoute =
  AdminVerificacionClientesIndexRouteImport.update({
    id: '/verificacion/clientes/',
    path: '/verificacion/clientes/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminVerificacionKybIndexRoute =
  AdminVerificacionKybIndexRouteImport.update({
    id: '/verificacion/kyb/',
    path: '/verificacion/kyb/',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/configuracion': typeof AdminConfiguracionRouteWithChildren
  '/legales/arrepentimiento': typeof LegalesArrepentimientoRoute
  '/legales/comisiones': typeof LegalesComisionesRoute
  '/legales/privacidad': typeof LegalesPrivacidadRoute
  '/legales/terminos': typeof LegalesTerminosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/administracion/usuarios': typeof AdminAdministracionUsuariosRouteWithChildren
  '/admin/estadisticas/depositos-retiros': typeof AdminEstadisticasDepositosRetirosRoute
  '/admin/estadisticas/indicadores': typeof AdminEstadisticasIndicadoresRoute
  '/admin/general/movimientos': typeof AdminGeneralMovimientosRouteWithChildren
  '/admin/general/usuarios': typeof AdminGeneralUsuariosRouteWithChildren
  '/admin/otc/tasas': typeof AdminOtcTasasRoute
  '/admin/pagos/aprobacion': typeof AdminPagosAprobacionRoute
  '/admin/pagos/metodos': typeof AdminPagosMetodosRoute
  '/admin/verificacion/identidad': typeof AdminVerificacionIdentidadRoute
  '/admin/verificacion/listas': typeof AdminVerificacionListasRoute
  '/admin/configuracion/': typeof AdminConfiguracionIndexRoute
  '/admin/administracion/usuarios/operadores': typeof AdminAdministracionUsuariosOperadoresRoute
  '/admin/administracion/usuarios/roles': typeof AdminAdministracionUsuariosRolesRoute
  '/admin/general/movimientos/comisiones': typeof AdminGeneralMovimientosComisionesRoute
  '/admin/general/movimientos/depositos': typeof AdminGeneralMovimientosDepositosRoute
  '/admin/general/movimientos/retiros': typeof AdminGeneralMovimientosRetirosRoute
  '/admin/administracion/usuarios/': typeof AdminAdministracionUsuariosIndexRoute
  '/admin/general/movimientos/': typeof AdminGeneralMovimientosIndexRoute
  '/admin/general/usuarios/': typeof AdminGeneralUsuariosIndexRoute
  '/admin/otc/registro/': typeof AdminOtcRegistroIndexRoute
  '/admin/verificacion/clientes/': typeof AdminVerificacionClientesIndexRoute
  '/admin/verificacion/kyb/': typeof AdminVerificacionKybIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/legales/arrepentimiento': typeof LegalesArrepentimientoRoute
  '/legales/comisiones': typeof LegalesComisionesRoute
  '/legales/privacidad': typeof LegalesPrivacidadRoute
  '/legales/terminos': typeof LegalesTerminosRoute
  '/admin': typeof AdminIndexRoute
  '/admin/estadisticas/depositos-retiros': typeof AdminEstadisticasDepositosRetirosRoute
  '/admin/estadisticas/indicadores': typeof AdminEstadisticasIndicadoresRoute
  '/admin/otc/tasas': typeof AdminOtcTasasRoute
  '/admin/pagos/aprobacion': typeof AdminPagosAprobacionRoute
  '/admin/pagos/metodos': typeof AdminPagosMetodosRoute
  '/admin/verificacion/identidad': typeof AdminVerificacionIdentidadRoute
  '/admin/verificacion/listas': typeof AdminVerificacionListasRoute
  '/admin/configuracion': typeof AdminConfiguracionIndexRoute
  '/admin/administracion/usuarios/operadores': typeof AdminAdministracionUsuariosOperadoresRoute
  '/admin/administracion/usuarios/roles': typeof AdminAdministracionUsuariosRolesRoute
  '/admin/general/movimientos/comisiones': typeof AdminGeneralMovimientosComisionesRoute
  '/admin/general/movimientos/depositos': typeof AdminGeneralMovimientosDepositosRoute
  '/admin/general/movimientos/retiros': typeof AdminGeneralMovimientosRetirosRoute
  '/admin/administracion/usuarios': typeof AdminAdministracionUsuariosIndexRoute
  '/admin/general/movimientos': typeof AdminGeneralMovimientosIndexRoute
  '/admin/general/usuarios': typeof AdminGeneralUsuariosIndexRoute
  '/admin/otc/registro': typeof AdminOtcRegistroIndexRoute
  '/admin/verificacion/clientes': typeof AdminVerificacionClientesIndexRoute
  '/admin/verificacion/kyb': typeof AdminVerificacionKybIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/configuracion': typeof AdminConfiguracionRouteWithChildren
  '/legales/arrepentimiento': typeof LegalesArrepentimientoRoute
  '/legales/comisiones': typeof LegalesComisionesRoute
  '/legales/privacidad': typeof LegalesPrivacidadRoute
  '/legales/terminos': typeof LegalesTerminosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/administracion/usuarios': typeof AdminAdministracionUsuariosRouteWithChildren
  '/admin/estadisticas/depositos-retiros': typeof AdminEstadisticasDepositosRetirosRoute
  '/admin/estadisticas/indicadores': typeof AdminEstadisticasIndicadoresRoute
  '/admin/general/movimientos': typeof AdminGeneralMovimientosRouteWithChildren
  '/admin/general/usuarios': typeof AdminGeneralUsuariosRouteWithChildren
  '/admin/otc/tasas': typeof AdminOtcTasasRoute
  '/admin/pagos/aprobacion': typeof AdminPagosAprobacionRoute
  '/admin/pagos/metodos': typeof AdminPagosMetodosRoute
  '/admin/verificacion/identidad': typeof AdminVerificacionIdentidadRoute
  '/admin/verificacion/listas': typeof AdminVerificacionListasRoute
  '/admin/configuracion/': typeof AdminConfiguracionIndexRoute
  '/admin/administracion/usuarios/operadores': typeof AdminAdministracionUsuariosOperadoresRoute
  '/admin/administracion/usuarios/roles': typeof AdminAdministracionUsuariosRolesRoute
  '/admin/general/movimientos/comisiones': typeof AdminGeneralMovimientosComisionesRoute
  '/admin/general/movimientos/depositos': typeof AdminGeneralMovimientosDepositosRoute
  '/admin/general/movimientos/retiros': typeof AdminGeneralMovimientosRetirosRoute
  '/admin/administracion/usuarios/': typeof AdminAdministracionUsuariosIndexRoute
  '/admin/general/movimientos/': typeof AdminGeneralMovimientosIndexRoute
  '/admin/general/usuarios/': typeof AdminGeneralUsuariosIndexRoute
  '/admin/otc/registro/': typeof AdminOtcRegistroIndexRoute
  '/admin/verificacion/clientes/': typeof AdminVerificacionClientesIndexRoute
  '/admin/verificacion/kyb/': typeof AdminVerificacionKybIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/configuracion'
    | '/legales/arrepentimiento'
    | '/legales/comisiones'
    | '/legales/privacidad'
    | '/legales/terminos'
    | '/admin/'
    | '/admin/administracion/usuarios'
    | '/admin/estadisticas/depositos-retiros'
    | '/admin/estadisticas/indicadores'
    | '/admin/general/movimientos'
    | '/admin/general/usuarios'
    | '/admin/otc/tasas'
    | '/admin/pagos/aprobacion'
    | '/admin/pagos/metodos'
    | '/admin/verificacion/identidad'
    | '/admin/verificacion/listas'
    | '/admin/configuracion/'
    | '/admin/administracion/usuarios/operadores'
    | '/admin/administracion/usuarios/roles'
    | '/admin/general/movimientos/comisiones'
    | '/admin/general/movimientos/depositos'
    | '/admin/general/movimientos/retiros'
    | '/admin/administracion/usuarios/'
    | '/admin/general/movimientos/'
    | '/admin/general/usuarios/'
    | '/admin/otc/registro/'
    | '/admin/verificacion/clientes/'
    | '/admin/verificacion/kyb/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/legales/arrepentimiento'
    | '/legales/comisiones'
    | '/legales/privacidad'
    | '/legales/terminos'
    | '/admin'
    | '/admin/estadisticas/depositos-retiros'
    | '/admin/estadisticas/indicadores'
    | '/admin/otc/tasas'
    | '/admin/pagos/aprobacion'
    | '/admin/pagos/metodos'
    | '/admin/verificacion/identidad'
    | '/admin/verificacion/listas'
    | '/admin/configuracion'
    | '/admin/administracion/usuarios/operadores'
    | '/admin/administracion/usuarios/roles'
    | '/admin/general/movimientos/comisiones'
    | '/admin/general/movimientos/depositos'
    | '/admin/general/movimientos/retiros'
    | '/admin/administracion/usuarios'
    | '/admin/general/movimientos'
    | '/admin/general/usuarios'
    | '/admin/otc/registro'
    | '/admin/verificacion/clientes'
    | '/admin/verificacion/kyb'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/configuracion'
    | '/legales/arrepentimiento'
    | '/legales/comisiones'
    | '/legales/privacidad'
    | '/legales/terminos'
    | '/admin/'
    | '/admin/administracion/usuarios'
    | '/admin/estadisticas/depositos-retiros'
    | '/admin/estadisticas/indicadores'
    | '/admin/general/movimientos'
    | '/admin/general/usuarios'
    | '/admin/otc/tasas'
    | '/admin/pagos/aprobacion'
    | '/admin/pagos/metodos'
    | '/admin/verificacion/identidad'
    | '/admin/verificacion/listas'
    | '/admin/configuracion/'
    | '/admin/administracion/usuarios/operadores'
    | '/admin/administracion/usuarios/roles'
    | '/admin/general/movimientos/comisiones'
    | '/admin/general/movimientos/depositos'
    | '/admin/general/movimientos/retiros'
    | '/admin/administracion/usuarios/'
    | '/admin/general/movimientos/'
    | '/admin/general/usuarios/'
    | '/admin/otc/registro/'
    | '/admin/verificacion/clientes/'
    | '/admin/verificacion/kyb/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  LegalesArrepentimientoRoute: typeof LegalesArrepentimientoRoute
  LegalesComisionesRoute: typeof LegalesComisionesRoute
  LegalesPrivacidadRoute: typeof LegalesPrivacidadRoute
  LegalesTerminosRoute: typeof LegalesTerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/legales/arrepentimiento': {
      id: '/legales/arrepentimiento'
      path: '/legales/arrepentimiento'
      fullPath: '/legales/arrepentimiento'
      preLoaderRoute: typeof LegalesArrepentimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legales/comisiones': {
      id: '/legales/comisiones'
      path: '/legales/comisiones'
      fullPath: '/legales/comisiones'
      preLoaderRoute: typeof LegalesComisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legales/privacidad': {
      id: '/legales/privacidad'
      path: '/legales/privacidad'
      fullPath: '/legales/privacidad'
      preLoaderRoute: typeof LegalesPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legales/terminos': {
      id: '/legales/terminos'
      path: '/legales/terminos'
      fullPath: '/legales/terminos'
      preLoaderRoute: typeof LegalesTerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/administracion/usuarios': {
      id: '/admin/administracion/usuarios'
      path: '/administracion/usuarios'
      fullPath: '/admin/administracion/usuarios'
      preLoaderRoute: typeof AdminAdministracionUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion/': {
      id: '/admin/configuracion/'
      path: '/'
      fullPath: '/admin/configuracion/'
      preLoaderRoute: typeof AdminConfiguracionIndexRouteImport
      parentRoute: typeof AdminConfiguracionRoute
    }
    '/admin/estadisticas/depositos-retiros': {
      id: '/admin/estadisticas/depositos-retiros'
      path: '/estadisticas/depositos-retiros'
      fullPath: '/admin/estadisticas/depositos-retiros'
      preLoaderRoute: typeof AdminEstadisticasDepositosRetirosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estadisticas/indicadores': {
      id: '/admin/estadisticas/indicadores'
      path: '/estadisticas/indicadores'
      fullPath: '/admin/estadisticas/indicadores'
      preLoaderRoute: typeof AdminEstadisticasIndicadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/general/movimientos': {
      id: '/admin/general/movimientos'
      path: '/general/movimientos'
      fullPath: '/admin/general/movimientos'
      preLoaderRoute: typeof AdminGeneralMovimientosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/general/usuarios': {
      id: '/admin/general/usuarios'
      path: '/general/usuarios'
      fullPath: '/admin/general/usuarios'
      preLoaderRoute: typeof AdminGeneralUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/otc/tasas': {
      id: '/admin/otc/tasas'
      path: '/otc/tasas'
      fullPath: '/admin/otc/tasas'
      preLoaderRoute: typeof AdminOtcTasasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagos/aprobacion': {
      id: '/admin/pagos/aprobacion'
      path: '/pagos/aprobacion'
      fullPath: '/admin/pagos/aprobacion'
      preLoaderRoute: typeof AdminPagosAprobacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagos/metodos': {
      id: '/admin/pagos/metodos'
      path: '/pagos/metodos'
      fullPath: '/admin/pagos/metodos'
      preLoaderRoute: typeof AdminPagosMetodosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verificacion/identidad': {
      id: '/admin/verificacion/identidad'
      path: '/verificacion/identidad'
      fullPath: '/admin/verificacion/identidad'
      preLoaderRoute: typeof AdminVerificacionIdentidadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verificacion/listas': {
      id: '/admin/verificacion/listas'
      path: '/verificacion/listas'
      fullPath: '/admin/verificacion/listas'
      preLoaderRoute: typeof AdminVerificacionListasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administracion/usuarios/': {
      id: '/admin/administracion/usuarios/'
      path: '/'
      fullPath: '/admin/administracion/usuarios/'
      preLoaderRoute: typeof AdminAdministracionUsuariosIndexRouteImport
      parentRoute: typeof AdminAdministracionUsuariosRoute
    }
    '/admin/administracion/usuarios/operadores': {
      id: '/admin/administracion/usuarios/operadores'
      path: '/operadores'
      fullPath: '/admin/administracion/usuarios/operadores'
      preLoaderRoute: typeof AdminAdministracionUsuariosOperadoresRouteImport
      parentRoute: typeof AdminAdministracionUsuariosRoute
    }
    '/admin/administracion/usuarios/roles': {
      id: '/admin/administracion/usuarios/roles'
      path: '/roles'
      fullPath: '/admin/administracion/usuarios/roles'
      preLoaderRoute: typeof AdminAdministracionUsuariosRolesRouteImport
      parentRoute: typeof AdminAdministracionUsuariosRoute
    }
    '/admin/general/movimientos/': {
      id: '/admin/general/movimientos/'
      path: '/'
      fullPath: '/admin/general/movimientos/'
      preLoaderRoute: typeof AdminGeneralMovimientosIndexRouteImport
      parentRoute: typeof AdminGeneralMovimientosRoute
    }
    '/admin/general/movimientos/comisiones': {
      id: '/admin/general/movimientos/comisiones'
      path: '/comisiones'
      fullPath: '/admin/general/movimientos/comisiones'
      preLoaderRoute: typeof AdminGeneralMovimientosComisionesRouteImport
      parentRoute: typeof AdminGeneralMovimientosRoute
    }
    '/admin/general/movimientos/depositos': {
      id: '/admin/general/movimientos/depositos'
      path: '/depositos'
      fullPath: '/admin/general/movimientos/depositos'
      preLoaderRoute: typeof AdminGeneralMovimientosDepositosRouteImport
      parentRoute: typeof AdminGeneralMovimientosRoute
    }
    '/admin/general/movimientos/retiros': {
      id: '/admin/general/movimientos/retiros'
      path: '/retiros'
      fullPath: '/admin/general/movimientos/retiros'
      preLoaderRoute: typeof AdminGeneralMovimientosRetirosRouteImport
      parentRoute: typeof AdminGeneralMovimientosRoute
    }
    '/admin/general/usuarios/': {
      id: '/admin/general/usuarios/'
      path: '/'
      fullPath: '/admin/general/usuarios/'
      preLoaderRoute: typeof AdminGeneralUsuariosIndexRouteImport
      parentRoute: typeof AdminGeneralUsuariosRoute
    }
    '/admin/otc/registro/': {
      id: '/admin/otc/registro/'
      path: '/otc/registro'
      fullPath: '/admin/otc/registro/'
      preLoaderRoute: typeof AdminOtcRegistroIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verificacion/clientes/': {
      id: '/admin/verificacion/clientes/'
      path: '/verificacion/clientes'
      fullPath: '/admin/verificacion/clientes/'
      preLoaderRoute: typeof AdminVerificacionClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verificacion/kyb/': {
      id: '/admin/verificacion/kyb/'
      path: '/verificacion/kyb'
      fullPath: '/admin/verificacion/kyb/'
      preLoaderRoute: typeof AdminVerificacionKybIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminConfiguracionRouteChildren {
  AdminConfiguracionIndexRoute: typeof AdminConfiguracionIndexRoute
}

const AdminConfiguracionRouteChildren: AdminConfiguracionRouteChildren = {
  AdminConfiguracionIndexRoute: AdminConfiguracionIndexRoute,
}

const AdminConfiguracionRouteWithChildren =
  AdminConfiguracionRoute._addFileChildren(AdminConfiguracionRouteChildren)

interface AdminAdministracionUsuariosRouteChildren {
  AdminAdministracionUsuariosOperadoresRoute: typeof AdminAdministracionUsuariosOperadoresRoute
  AdminAdministracionUsuariosRolesRoute: typeof AdminAdministracionUsuariosRolesRoute
  AdminAdministracionUsuariosIndexRoute: typeof AdminAdministracionUsuariosIndexRoute
}

const AdminAdministracionUsuariosRouteChildren: AdminAdministracionUsuariosRouteChildren =
  {
    AdminAdministracionUsuariosOperadoresRoute:
      AdminAdministracionUsuariosOperadoresRoute,
    AdminAdministracionUsuariosRolesRoute:
      AdminAdministracionUsuariosRolesRoute,
    AdminAdministracionUsuariosIndexRoute:
      AdminAdministracionUsuariosIndexRoute,
  }

const AdminAdministracionUsuariosRouteWithChildren =
  AdminAdministracionUsuariosRoute._addFileChildren(
    AdminAdministracionUsuariosRouteChildren,
  )

interface AdminGeneralMovimientosRouteChildren {
  AdminGeneralMovimientosComisionesRoute: typeof AdminGeneralMovimientosComisionesRoute
  AdminGeneralMovimientosDepositosRoute: typeof AdminGeneralMovimientosDepositosRoute
  AdminGeneralMovimientosRetirosRoute: typeof AdminGeneralMovimientosRetirosRoute
  AdminGeneralMovimientosIndexRoute: typeof AdminGeneralMovimientosIndexRoute
}

const AdminGeneralMovimientosRouteChildren: AdminGeneralMovimientosRouteChildren =
  {
    AdminGeneralMovimientosComisionesRoute:
      AdminGeneralMovimientosComisionesRoute,
    AdminGeneralMovimientosDepositosRoute:
      AdminGeneralMovimientosDepositosRoute,
    AdminGeneralMovimientosRetirosRoute: AdminGeneralMovimientosRetirosRoute,
    AdminGeneralMovimientosIndexRoute: AdminGeneralMovimientosIndexRoute,
  }

const AdminGeneralMovimientosRouteWithChildren =
  AdminGeneralMovimientosRoute._addFileChildren(
    AdminGeneralMovimientosRouteChildren,
  )

interface AdminGeneralUsuariosRouteChildren {
  AdminGeneralUsuariosIndexRoute: typeof AdminGeneralUsuariosIndexRoute
}

const AdminGeneralUsuariosRouteChildren: AdminGeneralUsuariosRouteChildren = {
  AdminGeneralUsuariosIndexRoute: AdminGeneralUsuariosIndexRoute,
}

const AdminGeneralUsuariosRouteWithChildren =
  AdminGeneralUsuariosRoute._addFileChildren(AdminGeneralUsuariosRouteChildren)

interface AdminRouteChildren {
  AdminConfiguracionRoute: typeof AdminConfiguracionRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdministracionUsuariosRoute: typeof AdminAdministracionUsuariosRouteWithChildren
  AdminEstadisticasDepositosRetirosRoute: typeof AdminEstadisticasDepositosRetirosRoute
  AdminEstadisticasIndicadoresRoute: typeof AdminEstadisticasIndicadoresRoute
  AdminGeneralMovimientosRoute: typeof AdminGeneralMovimientosRouteWithChildren
  AdminGeneralUsuariosRoute: typeof AdminGeneralUsuariosRouteWithChildren
  AdminOtcTasasRoute: typeof AdminOtcTasasRoute
  AdminPagosAprobacionRoute: typeof AdminPagosAprobacionRoute
  AdminPagosMetodosRoute: typeof AdminPagosMetodosRoute
  AdminVerificacionIdentidadRoute: typeof AdminVerificacionIdentidadRoute
  AdminVerificacionListasRoute: typeof AdminVerificacionListasRoute
  AdminOtcRegistroIndexRoute: typeof AdminOtcRegistroIndexRoute
  AdminVerificacionClientesIndexRoute: typeof AdminVerificacionClientesIndexRoute
  AdminVerificacionKybIndexRoute: typeof AdminVerificacionKybIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracionRoute: AdminConfiguracionRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminAdministracionUsuariosRoute:
    AdminAdministracionUsuariosRouteWithChildren,
  AdminEstadisticasDepositosRetirosRoute:
    AdminEstadisticasDepositosRetirosRoute,
  AdminEstadisticasIndicadoresRoute: AdminEstadisticasIndicadoresRoute,
  AdminGeneralMovimientosRoute: AdminGeneralMovimientosRouteWithChildren,
  AdminGeneralUsuariosRoute: AdminGeneralUsuariosRouteWithChildren,
  AdminOtcTasasRoute: AdminOtcTasasRoute,
  AdminPagosAprobacionRoute: AdminPagosAprobacionRoute,
  AdminPagosMetodosRoute: AdminPagosMetodosRoute,
  AdminVerificacionIdentidadRoute: AdminVerificacionIdentidadRoute,
  AdminVerificacionListasRoute: AdminVerificacionListasRoute,
  AdminOtcRegistroIndexRoute: AdminOtcRegistroIndexRoute,
  AdminVerificacionClientesIndexRoute: AdminVerificacionClientesIndexRoute,
  AdminVerificacionKybIndexRoute: AdminVerificacionKybIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  LegalesArrepentimientoRoute: LegalesArrepentimientoRoute,
  LegalesComisionesRoute: LegalesComisionesRoute,
  LegalesPrivacidadRoute: LegalesPrivacidadRoute,
  LegalesTerminosRoute: LegalesTerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
