/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminComerciosRouteImport } from './routes/admin.comercios'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminIncidentesRouteImport } from './routes/admin.incidentes'
import { Route as AdminModulosRouteImport } from './routes/admin.modulos'
import { Route as AdminNotificacionesRouteImport } from './routes/admin.notificaciones'
import { Route as LegalesArrepentimientoRouteImport } from './routes/legales.arrepentimiento'
import { Route as LegalesComisionesRouteImport } from './routes/legales.comisiones'
import { Route as LegalesPrivacidadRouteImport } from './routes/legales.privacidad'
import { Route as LegalesTerminosRouteImport } from './routes/legales.terminos'
import { Route as AdminAdministracionRegistrosRouteImport } from './routes/admin.administracion.registros'
import { Route as AdminAdministracionReportesRouteImport } from './routes/admin.administracion.reportes'
import { Route as AdminAdministracionSoporteRouteImport } from './routes/admin.administracion.soporte'
import { Route as AdminAdministracionUsuariosRouteImport } from './routes/admin.administracion.usuarios'
import { Route as AdminComerciosIndexRouteImport } from './routes/admin.comercios.index'
import { Route as AdminComerciosApisRouteImport } from './routes/admin.comercios.apis'
import { Route as AdminComerciosImpuestosRouteImport } from './routes/admin.comercios.impuestos'
import { Route as AdminComerciosLinkPagoRouteImport } from './routes/admin.comercios.link-pago'
import { Route as AdminComerciosTransferenciaRouteImport } from './routes/admin.comercios.transferencia'
import { Route as AdminConfiguracionIndexRouteImport } from './routes/admin.configuracion.index'
import { Route as AdminConfiguracionConfiguracionesRouteImport } from './routes/admin.configuracion.configuraciones'
import { Route as AdminConfiguracionLoginsRouteImport } from './routes/admin.configuracion.logins'
import { Route as AdminEstadisticasDepositosRetirosRouteImport } from './routes/admin.estadisticas.depositos-retiros'
import { Route as AdminEstadisticasIndicadoresRouteImport } from './routes/admin.estadisticas.indicadores'
import { Route as AdminGeneralAlertasRouteImport } from './routes/admin.general.alertas'
import { Route as AdminGeneralMovimientosRouteImport } from './routes/admin.general.movimientos'
import { Route as AdminGeneralUsuariosRouteImport } from './routes/admin.general.usuarios'
import { Route as AdminNotificacionesIndexRouteImport } from './routes/admin.notificaciones.index'
import { Route as AdminOtcTasasRouteImport } from './routes/admin.otc.tasas'
import { Route as AdminPagosAprobacionRouteImport } from './routes/admin.pagos.aprobacion'
import { Route as AdminPagosComprobantesRouteImport } from './routes/admin.pagos.comprobantes'
import { Route as AdminVerificacionIdentidadRouteImport } from './routes/admin.verificacion.identidad'
import { Route as AdminVerificacionListasRouteImport } from './routes/admin.verificacion.listas'
import { Route as AdminAdministracionRegistrosIndexRouteImport } from './routes/admin.administracion.registros.index'
import { Route as AdminAdministracionRegistrosActividadRouteImport } from './routes/admin.administracion.registros.actividad'
import { Route as AdminAdministracionRegistrosTotalRouteImport } from './routes/admin.administracion.registros.total'
import { Route as AdminAdministracionSoporteIndexRouteImport } from './routes/admin.administracion.soporte.index'
import { Route as AdminAdministracionSoporteBloqueoRouteImport } from './routes/admin.administracion.soporte.bloqueo'
import { Route as AdminAdministracionUsuariosIndexRouteImport } from './routes/admin.administracion.usuarios.index'
import { Route as AdminAdministracionUsuariosRolesRouteImport } from './routes/admin.administracion.usuarios.roles'
import { Route as AdminComerciosApisIndexRouteImport } from './routes/admin.comercios.apis.index'
import { Route as AdminComerciosApisEndpointsRouteImport } from './routes/admin.comercios.apis.endpoints'
import { Route as AdminComerciosApisRestriccionesRouteImport } from './routes/admin.comercios.apis.restricciones'
import { Route as AdminComerciosImpuestosIndexRouteImport } from './routes/admin.comercios.impuestos.index'
import { Route as AdminComerciosImpuestosDebitosCreditosRouteImport } from './routes/admin.comercios.impuestos.debitos-creditos'
import { Route as AdminComerciosImpuestosIngresosBrutosRouteImport } from './routes/admin.comercios.impuestos.ingresos-brutos'
import { Route as AdminComerciosImpuestosUsuariosRouteImport } from './routes/admin.comercios.impuestos.usuarios'
import { Route as AdminComerciosTransferenciaIndexRouteImport } from './routes/admin.comercios.transferencia.index'
import { Route as AdminComerciosTransferenciaCategoriasRouteImport } from './routes/admin.comercios.transferencia.categorias'
import { Route as AdminComerciosTransferenciaResolversRouteImport } from './routes/admin.comercios.transferencia.resolvers'
import { Route as AdminGeneralAlertasIndexRouteImport } from './routes/admin.general.alertas.index'
import { Route as AdminGeneralAlertasBloqueosRouteImport } from './routes/admin.general.alertas.bloqueos'
import { Route as AdminGeneralAlertasParametrosAlertasRouteImport } from './routes/admin.general.alertas.parametros-alertas'
import { Route as AdminGeneralAlertasParametrosBloqueosRouteImport } from './routes/admin.general.alertas.parametros-bloqueos'
import { Route as AdminGeneralMovimientosIndexRouteImport } from './routes/admin.general.movimientos.index'
import { Route as AdminGeneralMovimientosCobrosQrRouteImport } from './routes/admin.general.movimientos.cobros-qr'
import { Route as AdminGeneralMovimientosComisionesRouteImport } from './routes/admin.general.movimientos.comisiones'
import { Route as AdminGeneralMovimientosDepositosRouteImport } from './routes/admin.general.movimientos.depositos'
import { Route as AdminGeneralMovimientosImpuestosRouteImport } from './routes/admin.general.movimientos.impuestos'
import { Route as AdminGeneralMovimientosPagosQrRouteImport } from './routes/admin.general.movimientos.pagos-qr'
import { Route as AdminGeneralMovimientosPagosTarjetaRouteImport } from './routes/admin.general.movimientos.pagos-tarjeta'
import { Route as AdminGeneralMovimientosRetirosRouteImport } from './routes/admin.general.movimientos.retiros'
import { Route as AdminGeneralUsuariosIndexRouteImport } from './routes/admin.general.usuarios.index'
import { Route as AdminGeneralUsuariosLegajoRouteImport } from './routes/admin.general.usuarios.$legajo'
import { Route as AdminGeneralUsuariosComisionesRouteImport } from './routes/admin.general.usuarios.comisiones'
import { Route as AdminGeneralUsuariosCvuRouteImport } from './routes/admin.general.usuarios.cvu'
import { Route as AdminGeneralUsuariosJuridicasRouteImport } from './routes/admin.general.usuarios.juridicas'
import { Route as AdminOtcRegistroIndexRouteImport } from './routes/admin.otc.registro.index'
import { Route as AdminPagosSolicitudesIndexRouteImport } from './routes/admin.pagos.solicitudes.index'
import { Route as AdminVerificacionClientesIndexRouteImport } from './routes/admin.verificacion.clientes.index'
import { Route as AdminComerciosImpuestosIngresosBrutosIndexRouteImport } from './routes/admin.comercios.impuestos.ingresos-brutos.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComerciosRoute = AdminComerciosRouteImport.update({
  id: '/comercios',
  path: '/comercios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncidentesRoute = AdminIncidentesRouteImport.update({
  id: '/incidentes',
  path: '/incidentes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulosRoute = AdminModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacionesRoute = AdminNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AdminRoute,
} as any)
const LegalesArrepentimientoRoute = LegalesArrepentimientoRouteImport.update({
  id: '/legales/arrepentimiento',
  path: '/legales/arrepentimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalesComisionesRoute = LegalesComisionesRouteImport.update({
  id: '/legales/comisiones',
  path: '/legales/comisiones',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalesPrivacidadRoute = LegalesPrivacidadRouteImport.update({
  id: '/legales/privacidad',
  path: '/legales/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalesTerminosRoute = LegalesTerminosRouteImport.update({
  id: '/legales/terminos',
  path: '/legales/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdministracionRegistrosRoute =
  AdminAdministracionRegistrosRouteImport.update({
    id: '/administracion/registros',
    path: '/administracion/registros',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdministracionReportesRoute =
  AdminAdministracionReportesRouteImport.update({
    id: '/administracion/reportes',
    path: '/administracion/reportes',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdministracionSoporteRoute =
  AdminAdministracionSoporteRouteImport.update({
    id: '/administracion/soporte',
    path: '/administracion/soporte',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdministracionUsuariosRoute =
  AdminAdministracionUsuariosRouteImport.update({
    id: '/administracion/usuarios',
    path: '/administracion/usuarios',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminComerciosIndexRoute = AdminComerciosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminComerciosRoute,
} as any)
const AdminComerciosApisRoute = AdminComerciosApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => AdminComerciosRoute,
} as any)
const AdminComerciosImpuestosRoute = AdminComerciosImpuestosRouteImport.update({
  id: '/impuestos',
  path: '/impuestos',
  getParentRoute: () => AdminComerciosRoute,
} as any)
const AdminComerciosLinkPagoRoute = AdminComerciosLinkPagoRouteImport.update({
  id: '/link-pago',
  path: '/link-pago',
  getParentRoute: () => AdminComerciosRoute,
} as any)
const AdminComerciosTransferenciaRoute =
  AdminComerciosTransferenciaRouteImport.update({
    id: '/transferencia',
    path: '/transferencia',
    getParentRoute: () => AdminComerciosRoute,
  } as any)
const AdminConfiguracionIndexRoute = AdminConfiguracionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminConfiguracionRoute,
} as any)
const AdminConfiguracionConfiguracionesRoute =
  AdminConfiguracionConfiguracionesRouteImport.update({
    id: '/configuraciones',
    path: '/configuraciones',
    getParentRoute: () => AdminConfiguracionRoute,
  } as any)
const AdminConfiguracionLoginsRoute =
  AdminConfiguracionLoginsRouteImport.update({
    id: '/logins',
    path: '/logins',
    getParentRoute: () => AdminConfiguracionRoute,
  } as any)
const AdminEstadisticasDepositosRetirosRoute =
  AdminEstadisticasDepositosRetirosRouteImport.update({
    id: '/estadisticas/depositos-retiros',
    path: '/estadisticas/depositos-retiros',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEstadisticasIndicadoresRoute =
  AdminEstadisticasIndicadoresRouteImport.update({
    id: '/estadisticas/indicadores',
    path: '/estadisticas/indicadores',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminGeneralAlertasRoute = AdminGeneralAlertasRouteImport.update({
  id: '/general/alertas',
  path: '/general/alertas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeneralMovimientosRoute = AdminGeneralMovimientosRouteImport.update({
  id: '/general/movimientos',
  path: '/general/movimientos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeneralUsuariosRoute = AdminGeneralUsuariosRouteImport.update({
  id: '/general/usuarios',
  path: '/general/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacionesIndexRoute =
  AdminNotificacionesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminNotificacionesRoute,
  } as any)
const AdminOtcTasasRoute = AdminOtcTasasRouteImport.update({
  id: '/otc/tasas',
  path: '/otc/tasas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagosAprobacionRoute = AdminPagosAprobacionRouteImport.update({
  id: '/pagos/aprobacion',
  path: '/pagos/aprobacion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagosComprobantesRoute = AdminPagosComprobantesRouteImport.update({
  id: '/pagos/comprobantes',
  path: '/pagos/comprobantes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificacionIdentidadRoute =
  AdminVerificacionIdentidadRouteImport.update({
    id: '/verificacion/identidad',
    path: '/verificacion/identidad',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminVerificacionListasRoute = AdminVerificacionListasRouteImport.update({
  id: '/verificacion/listas',
  path: '/verificacion/listas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministracionRegistrosIndexRoute =
  AdminAdministracionRegistrosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdministracionRegistrosRoute,
  } as any)
const AdminAdministracionRegistrosActividadRoute =
  AdminAdministracionRegistrosActividadRouteImport.update({
    id: '/actividad',
    path: '/actividad',
    getParentRoute: () => AdminAdministracionRegistrosRoute,
  } as any)
const AdminAdministracionRegistrosTotalRoute =
  AdminAdministracionRegistrosTotalRouteImport.update({
    id: '/total',
    path: '/total',
    getParentRoute: () => AdminAdministracionRegistrosRoute,
  } as any)
const AdminAdministracionSoporteIndexRoute =
  AdminAdministracionSoporteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdministracionSoporteRoute,
  } as any)
const AdminAdministracionSoporteBloqueoRoute =
  AdminAdministracionSoporteBloqueoRouteImport.update({
    id: '/bloqueo',
    path: '/bloqueo',
    getParentRoute: () => AdminAdministracionSoporteRoute,
  } as any)
const AdminAdministracionUsuariosIndexRoute =
  AdminAdministracionUsuariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdministracionUsuariosRoute,
  } as any)
const AdminAdministracionUsuariosRolesRoute =
  AdminAdministracionUsuariosRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AdminAdministracionUsuariosRoute,
  } as any)
const AdminComerciosApisIndexRoute = AdminComerciosApisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminComerciosApisRoute,
} as any)
const AdminComerciosApisEndpointsRoute =
  AdminComerciosApisEndpointsRouteImport.update({
    id: '/endpoints',
    path: '/endpoints',
    getParentRoute: () => AdminComerciosApisRoute,
  } as any)
const AdminComerciosApisRestriccionesRoute =
  AdminComerciosApisRestriccionesRouteImport.update({
    id: '/restricciones',
    path: '/restricciones',
    getParentRoute: () => AdminComerciosApisRoute,
  } as any)
const AdminComerciosImpuestosIndexRoute =
  AdminComerciosImpuestosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminComerciosImpuestosRoute,
  } as any)
const AdminComerciosImpuestosDebitosCreditosRoute =
  AdminComerciosImpuestosDebitosCreditosRouteImport.update({
    id: '/debitos-creditos',
    path: '/debitos-creditos',
    getParentRoute: () => AdminComerciosImpuestosRoute,
  } as any)
const AdminComerciosImpuestosIngresosBrutosRoute =
  AdminComerciosImpuestosIngresosBrutosRouteImport.update({
    id: '/ingresos-brutos',
    path: '/ingresos-brutos',
    getParentRoute: () => AdminComerciosImpuestosRoute,
  } as any)
const AdminComerciosImpuestosUsuariosRoute =
  AdminComerciosImpuestosUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AdminComerciosImpuestosRoute,
  } as any)
const AdminComerciosTransferenciaIndexRoute =
  AdminComerciosTransferenciaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminComerciosTransferenciaRoute,
  } as any)
const AdminComerciosTransferenciaCategoriasRoute =
  AdminComerciosTransferenciaCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AdminComerciosTransferenciaRoute,
  } as any)
const AdminComerciosTransferenciaResolversRoute =
  AdminComerciosTransferenciaResolversRouteImport.update({
    id: '/resolvers',
    path: '/resolvers',
    getParentRoute: () => AdminComerciosTransferenciaRoute,
  } as any)
const AdminGeneralAlertasIndexRoute =
  AdminGeneralAlertasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminGeneralAlertasRoute,
  } as any)
const AdminGeneralAlertasBloqueosRoute =
  AdminGeneralAlertasBloqueosRouteImport.update({
    id: '/bloqueos',
    path: '/bloqueos',
    getParentRoute: () => AdminGeneralAlertasRoute,
  } as any)
const AdminGeneralAlertasParametrosAlertasRoute =
  AdminGeneralAlertasParametrosAlertasRouteImport.update({
    id: '/parametros-alertas',
    path: '/parametros-alertas',
    getParentRoute: () => AdminGeneralAlertasRoute,
  } as any)
const AdminGeneralAlertasParametrosBloqueosRoute =
  AdminGeneralAlertasParametrosBloqueosRouteImport.update({
    id: '/parametros-bloqueos',
    path: '/parametros-bloqueos',
    getParentRoute: () => AdminGeneralAlertasRoute,
  } as any)
const AdminGeneralMovimientosIndexRoute =
  AdminGeneralMovimientosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminGeneralMovimientosRoute,
  } as any)
const AdminGeneralMovimientosCobrosQrRoute =
  AdminGeneralMovimientosCobrosQrRouteImport.update({
    id: '/cobros-qr',
    path: '/cobros-qr',
    getParentRoute: () => AdminGeneralMovimientosRoute,
  } as any)
const AdminGeneralMovimientosComisionesRoute =
  AdminGeneralMovimientosComisionesRouteImport.update({
    id: '/comisiones',
    path: '/comisiones',
    getParentRoute: () => AdminGeneralMovimientosRoute,
  } as any)
const AdminGeneralMovimientosDepositosRoute =
  AdminGeneralMovimientosDepositosRouteImport.update({
    id: '/depositos',
    path: '/depositos',
    getParentRoute: () => AdminGeneralMovimientosRoute,
  } as any)
const AdminGeneralMovimientosImpuestosRoute =
  AdminGeneralMovimientosImpuestosRouteImport.update({
    id: '/impuestos',
    path: '/impuestos',
    getParentRoute: () => AdminGeneralMovimientosRoute,
  } as any)
const AdminGeneralMovimientosPagosQrRoute =
  AdminGeneralMovimientosPagosQrRouteImport.update({
    id: '/pagos-qr',
    path: '/pagos-qr',
    getParentRoute: () => AdminGeneralMovimientosRoute,
  } as any)
const AdminGeneralMovimientosPagosTarjetaRoute =
  AdminGeneralMovimientosPagosTarjetaRouteImport.update({
    id: '/pagos-tarjeta',
    path: '/pagos-tarjeta',
    getParentRoute: () => AdminGeneralMovimientosRoute,
  } as any)
const AdminGeneralMovimientosRetirosRoute =
  AdminGeneralMovimientosRetirosRouteImport.update({
    id: '/retiros',
    path: '/retiros',
    getParentRoute: () => AdminGeneralMovimientosRoute,
  } as any)
const AdminGeneralUsuariosIndexRoute =
  AdminGeneralUsuariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminGeneralUsuariosRoute,
  } as any)
const AdminGeneralUsuariosLegajoRoute =
  AdminGeneralUsuariosLegajoRouteImport.update({
    id: '/$legajo',
    path: '/$legajo',
    getParentRoute: () => AdminGeneralUsuariosRoute,
  } as any)
const AdminGeneralUsuariosComisionesRoute =
  AdminGeneralUsuariosComisionesRouteImport.update({
    id: '/comisiones',
    path: '/comisiones',
    getParentRoute: () => AdminGeneralUsuariosRoute,
  } as any)
const AdminGeneralUsuariosCvuRoute = AdminGeneralUsuariosCvuRouteImport.update({
  id: '/cvu',
  path: '/cvu',
  getParentRoute: () => AdminGeneralUsuariosRoute,
} as any)
const AdminGeneralUsuariosJuridicasRoute =
  AdminGeneralUsuariosJuridicasRouteImport.update({
    id: '/juridicas',
    path: '/juridicas',
    getParentRoute: () => AdminGeneralUsuariosRoute,
  } as any)
const AdminOtcRegistroIndexRoute = AdminOtcRegistroIndexRouteImport.update({
  id: '/otc/registro/',
  path: '/otc/registro/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagosSolicitudesIndexRoute =
  AdminPagosSolicitudesIndexRouteImport.update({
    id: '/pagos/solicitudes/',
    path: '/pagos/solicitudes/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminVerificacionClientesIndexRoute =
  AdminVerificacionClientesIndexRouteImport.update({
    id: '/verificacion/clientes/',
    path: '/verificacion/clientes/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminComerciosImpuestosIngresosBrutosIndexRoute =
  AdminComerciosImpuestosIngresosBrutosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminComerciosImpuestosIngresosBrutosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/comercios': typeof AdminComerciosRouteWithChildren
  '/admin/configuracion': typeof AdminConfiguracionRouteWithChildren
  '/admin/incidentes': typeof AdminIncidentesRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/notificaciones': typeof AdminNotificacionesRouteWithChildren
  '/legales/arrepentimiento': typeof LegalesArrepentimientoRoute
  '/legales/comisiones': typeof LegalesComisionesRoute
  '/legales/privacidad': typeof LegalesPrivacidadRoute
  '/legales/terminos': typeof LegalesTerminosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/administracion/registros': typeof AdminAdministracionRegistrosRouteWithChildren
  '/admin/administracion/reportes': typeof AdminAdministracionReportesRoute
  '/admin/administracion/soporte': typeof AdminAdministracionSoporteRouteWithChildren
  '/admin/administracion/usuarios': typeof AdminAdministracionUsuariosRouteWithChildren
  '/admin/comercios/apis': typeof AdminComerciosApisRouteWithChildren
  '/admin/comercios/impuestos': typeof AdminComerciosImpuestosRouteWithChildren
  '/admin/comercios/link-pago': typeof AdminComerciosLinkPagoRoute
  '/admin/comercios/transferencia': typeof AdminComerciosTransferenciaRouteWithChildren
  '/admin/configuracion/configuraciones': typeof AdminConfiguracionConfiguracionesRoute
  '/admin/configuracion/logins': typeof AdminConfiguracionLoginsRoute
  '/admin/estadisticas/depositos-retiros': typeof AdminEstadisticasDepositosRetirosRoute
  '/admin/estadisticas/indicadores': typeof AdminEstadisticasIndicadoresRoute
  '/admin/general/alertas': typeof AdminGeneralAlertasRouteWithChildren
  '/admin/general/movimientos': typeof AdminGeneralMovimientosRouteWithChildren
  '/admin/general/usuarios': typeof AdminGeneralUsuariosRouteWithChildren
  '/admin/otc/tasas': typeof AdminOtcTasasRoute
  '/admin/pagos/aprobacion': typeof AdminPagosAprobacionRoute
  '/admin/pagos/comprobantes': typeof AdminPagosComprobantesRoute
  '/admin/verificacion/identidad': typeof AdminVerificacionIdentidadRoute
  '/admin/verificacion/listas': typeof AdminVerificacionListasRoute
  '/admin/comercios/': typeof AdminComerciosIndexRoute
  '/admin/configuracion/': typeof AdminConfiguracionIndexRoute
  '/admin/notificaciones/': typeof AdminNotificacionesIndexRoute
  '/admin/administracion/registros/actividad': typeof AdminAdministracionRegistrosActividadRoute
  '/admin/administracion/registros/total': typeof AdminAdministracionRegistrosTotalRoute
  '/admin/administracion/soporte/bloqueo': typeof AdminAdministracionSoporteBloqueoRoute
  '/admin/administracion/usuarios/roles': typeof AdminAdministracionUsuariosRolesRoute
  '/admin/comercios/apis/endpoints': typeof AdminComerciosApisEndpointsRoute
  '/admin/comercios/apis/restricciones': typeof AdminComerciosApisRestriccionesRoute
  '/admin/comercios/impuestos/debitos-creditos': typeof AdminComerciosImpuestosDebitosCreditosRoute
  '/admin/comercios/impuestos/ingresos-brutos': typeof AdminComerciosImpuestosIngresosBrutosRouteWithChildren
  '/admin/comercios/impuestos/usuarios': typeof AdminComerciosImpuestosUsuariosRoute
  '/admin/comercios/transferencia/categorias': typeof AdminComerciosTransferenciaCategoriasRoute
  '/admin/comercios/transferencia/resolvers': typeof AdminComerciosTransferenciaResolversRoute
  '/admin/general/alertas/bloqueos': typeof AdminGeneralAlertasBloqueosRoute
  '/admin/general/alertas/parametros-alertas': typeof AdminGeneralAlertasParametrosAlertasRoute
  '/admin/general/alertas/parametros-bloqueos': typeof AdminGeneralAlertasParametrosBloqueosRoute
  '/admin/general/movimientos/cobros-qr': typeof AdminGeneralMovimientosCobrosQrRoute
  '/admin/general/movimientos/comisiones': typeof AdminGeneralMovimientosComisionesRoute
  '/admin/general/movimientos/depositos': typeof AdminGeneralMovimientosDepositosRoute
  '/admin/general/movimientos/impuestos': typeof AdminGeneralMovimientosImpuestosRoute
  '/admin/general/movimientos/pagos-qr': typeof AdminGeneralMovimientosPagosQrRoute
  '/admin/general/movimientos/pagos-tarjeta': typeof AdminGeneralMovimientosPagosTarjetaRoute
  '/admin/general/movimientos/retiros': typeof AdminGeneralMovimientosRetirosRoute
  '/admin/general/usuarios/$legajo': typeof AdminGeneralUsuariosLegajoRoute
  '/admin/general/usuarios/comisiones': typeof AdminGeneralUsuariosComisionesRoute
  '/admin/general/usuarios/cvu': typeof AdminGeneralUsuariosCvuRoute
  '/admin/general/usuarios/juridicas': typeof AdminGeneralUsuariosJuridicasRoute
  '/admin/administracion/registros/': typeof AdminAdministracionRegistrosIndexRoute
  '/admin/administracion/soporte/': typeof AdminAdministracionSoporteIndexRoute
  '/admin/administracion/usuarios/': typeof AdminAdministracionUsuariosIndexRoute
  '/admin/comercios/apis/': typeof AdminComerciosApisIndexRoute
  '/admin/comercios/impuestos/': typeof AdminComerciosImpuestosIndexRoute
  '/admin/comercios/transferencia/': typeof AdminComerciosTransferenciaIndexRoute
  '/admin/general/alertas/': typeof AdminGeneralAlertasIndexRoute
  '/admin/general/movimientos/': typeof AdminGeneralMovimientosIndexRoute
  '/admin/general/usuarios/': typeof AdminGeneralUsuariosIndexRoute
  '/admin/otc/registro/': typeof AdminOtcRegistroIndexRoute
  '/admin/pagos/solicitudes/': typeof AdminPagosSolicitudesIndexRoute
  '/admin/verificacion/clientes/': typeof AdminVerificacionClientesIndexRoute
  '/admin/comercios/impuestos/ingresos-brutos/': typeof AdminComerciosImpuestosIngresosBrutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/incidentes': typeof AdminIncidentesRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/legales/arrepentimiento': typeof LegalesArrepentimientoRoute
  '/legales/comisiones': typeof LegalesComisionesRoute
  '/legales/privacidad': typeof LegalesPrivacidadRoute
  '/legales/terminos': typeof LegalesTerminosRoute
  '/admin': typeof AdminIndexRoute
  '/admin/administracion/reportes': typeof AdminAdministracionReportesRoute
  '/admin/comercios/link-pago': typeof AdminComerciosLinkPagoRoute
  '/admin/configuracion/configuraciones': typeof AdminConfiguracionConfiguracionesRoute
  '/admin/configuracion/logins': typeof AdminConfiguracionLoginsRoute
  '/admin/estadisticas/depositos-retiros': typeof AdminEstadisticasDepositosRetirosRoute
  '/admin/estadisticas/indicadores': typeof AdminEstadisticasIndicadoresRoute
  '/admin/otc/tasas': typeof AdminOtcTasasRoute
  '/admin/pagos/aprobacion': typeof AdminPagosAprobacionRoute
  '/admin/pagos/comprobantes': typeof AdminPagosComprobantesRoute
  '/admin/verificacion/identidad': typeof AdminVerificacionIdentidadRoute
  '/admin/verificacion/listas': typeof AdminVerificacionListasRoute
  '/admin/comercios': typeof AdminComerciosIndexRoute
  '/admin/configuracion': typeof AdminConfiguracionIndexRoute
  '/admin/notificaciones': typeof AdminNotificacionesIndexRoute
  '/admin/administracion/registros/actividad': typeof AdminAdministracionRegistrosActividadRoute
  '/admin/administracion/registros/total': typeof AdminAdministracionRegistrosTotalRoute
  '/admin/administracion/soporte/bloqueo': typeof AdminAdministracionSoporteBloqueoRoute
  '/admin/administracion/usuarios/roles': typeof AdminAdministracionUsuariosRolesRoute
  '/admin/comercios/apis/endpoints': typeof AdminComerciosApisEndpointsRoute
  '/admin/comercios/apis/restricciones': typeof AdminComerciosApisRestriccionesRoute
  '/admin/comercios/impuestos/debitos-creditos': typeof AdminComerciosImpuestosDebitosCreditosRoute
  '/admin/comercios/impuestos/usuarios': typeof AdminComerciosImpuestosUsuariosRoute
  '/admin/comercios/transferencia/categorias': typeof AdminComerciosTransferenciaCategoriasRoute
  '/admin/comercios/transferencia/resolvers': typeof AdminComerciosTransferenciaResolversRoute
  '/admin/general/alertas/bloqueos': typeof AdminGeneralAlertasBloqueosRoute
  '/admin/general/alertas/parametros-alertas': typeof AdminGeneralAlertasParametrosAlertasRoute
  '/admin/general/alertas/parametros-bloqueos': typeof AdminGeneralAlertasParametrosBloqueosRoute
  '/admin/general/movimientos/cobros-qr': typeof AdminGeneralMovimientosCobrosQrRoute
  '/admin/general/movimientos/comisiones': typeof AdminGeneralMovimientosComisionesRoute
  '/admin/general/movimientos/depositos': typeof AdminGeneralMovimientosDepositosRoute
  '/admin/general/movimientos/impuestos': typeof AdminGeneralMovimientosImpuestosRoute
  '/admin/general/movimientos/pagos-qr': typeof AdminGeneralMovimientosPagosQrRoute
  '/admin/general/movimientos/pagos-tarjeta': typeof AdminGeneralMovimientosPagosTarjetaRoute
  '/admin/general/movimientos/retiros': typeof AdminGeneralMovimientosRetirosRoute
  '/admin/general/usuarios/$legajo': typeof AdminGeneralUsuariosLegajoRoute
  '/admin/general/usuarios/comisiones': typeof AdminGeneralUsuariosComisionesRoute
  '/admin/general/usuarios/cvu': typeof AdminGeneralUsuariosCvuRoute
  '/admin/general/usuarios/juridicas': typeof AdminGeneralUsuariosJuridicasRoute
  '/admin/administracion/registros': typeof AdminAdministracionRegistrosIndexRoute
  '/admin/administracion/soporte': typeof AdminAdministracionSoporteIndexRoute
  '/admin/administracion/usuarios': typeof AdminAdministracionUsuariosIndexRoute
  '/admin/comercios/apis': typeof AdminComerciosApisIndexRoute
  '/admin/comercios/impuestos': typeof AdminComerciosImpuestosIndexRoute
  '/admin/comercios/transferencia': typeof AdminComerciosTransferenciaIndexRoute
  '/admin/general/alertas': typeof AdminGeneralAlertasIndexRoute
  '/admin/general/movimientos': typeof AdminGeneralMovimientosIndexRoute
  '/admin/general/usuarios': typeof AdminGeneralUsuariosIndexRoute
  '/admin/otc/registro': typeof AdminOtcRegistroIndexRoute
  '/admin/pagos/solicitudes': typeof AdminPagosSolicitudesIndexRoute
  '/admin/verificacion/clientes': typeof AdminVerificacionClientesIndexRoute
  '/admin/comercios/impuestos/ingresos-brutos': typeof AdminComerciosImpuestosIngresosBrutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/comercios': typeof AdminComerciosRouteWithChildren
  '/admin/configuracion': typeof AdminConfiguracionRouteWithChildren
  '/admin/incidentes': typeof AdminIncidentesRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/notificaciones': typeof AdminNotificacionesRouteWithChildren
  '/legales/arrepentimiento': typeof LegalesArrepentimientoRoute
  '/legales/comisiones': typeof LegalesComisionesRoute
  '/legales/privacidad': typeof LegalesPrivacidadRoute
  '/legales/terminos': typeof LegalesTerminosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/administracion/registros': typeof AdminAdministracionRegistrosRouteWithChildren
  '/admin/administracion/reportes': typeof AdminAdministracionReportesRoute
  '/admin/administracion/soporte': typeof AdminAdministracionSoporteRouteWithChildren
  '/admin/administracion/usuarios': typeof AdminAdministracionUsuariosRouteWithChildren
  '/admin/comercios/apis': typeof AdminComerciosApisRouteWithChildren
  '/admin/comercios/impuestos': typeof AdminComerciosImpuestosRouteWithChildren
  '/admin/comercios/link-pago': typeof AdminComerciosLinkPagoRoute
  '/admin/comercios/transferencia': typeof AdminComerciosTransferenciaRouteWithChildren
  '/admin/configuracion/configuraciones': typeof AdminConfiguracionConfiguracionesRoute
  '/admin/configuracion/logins': typeof AdminConfiguracionLoginsRoute
  '/admin/estadisticas/depositos-retiros': typeof AdminEstadisticasDepositosRetirosRoute
  '/admin/estadisticas/indicadores': typeof AdminEstadisticasIndicadoresRoute
  '/admin/general/alertas': typeof AdminGeneralAlertasRouteWithChildren
  '/admin/general/movimientos': typeof AdminGeneralMovimientosRouteWithChildren
  '/admin/general/usuarios': typeof AdminGeneralUsuariosRouteWithChildren
  '/admin/otc/tasas': typeof AdminOtcTasasRoute
  '/admin/pagos/aprobacion': typeof AdminPagosAprobacionRoute
  '/admin/pagos/comprobantes': typeof AdminPagosComprobantesRoute
  '/admin/verificacion/identidad': typeof AdminVerificacionIdentidadRoute
  '/admin/verificacion/listas': typeof AdminVerificacionListasRoute
  '/admin/comercios/': typeof AdminComerciosIndexRoute
  '/admin/configuracion/': typeof AdminConfiguracionIndexRoute
  '/admin/notificaciones/': typeof AdminNotificacionesIndexRoute
  '/admin/administracion/registros/actividad': typeof AdminAdministracionRegistrosActividadRoute
  '/admin/administracion/registros/total': typeof AdminAdministracionRegistrosTotalRoute
  '/admin/administracion/soporte/bloqueo': typeof AdminAdministracionSoporteBloqueoRoute
  '/admin/administracion/usuarios/roles': typeof AdminAdministracionUsuariosRolesRoute
  '/admin/comercios/apis/endpoints': typeof AdminComerciosApisEndpointsRoute
  '/admin/comercios/apis/restricciones': typeof AdminComerciosApisRestriccionesRoute
  '/admin/comercios/impuestos/debitos-creditos': typeof AdminComerciosImpuestosDebitosCreditosRoute
  '/admin/comercios/impuestos/ingresos-brutos': typeof AdminComerciosImpuestosIngresosBrutosRouteWithChildren
  '/admin/comercios/impuestos/usuarios': typeof AdminComerciosImpuestosUsuariosRoute
  '/admin/comercios/transferencia/categorias': typeof AdminComerciosTransferenciaCategoriasRoute
  '/admin/comercios/transferencia/resolvers': typeof AdminComerciosTransferenciaResolversRoute
  '/admin/general/alertas/bloqueos': typeof AdminGeneralAlertasBloqueosRoute
  '/admin/general/alertas/parametros-alertas': typeof AdminGeneralAlertasParametrosAlertasRoute
  '/admin/general/alertas/parametros-bloqueos': typeof AdminGeneralAlertasParametrosBloqueosRoute
  '/admin/general/movimientos/cobros-qr': typeof AdminGeneralMovimientosCobrosQrRoute
  '/admin/general/movimientos/comisiones': typeof AdminGeneralMovimientosComisionesRoute
  '/admin/general/movimientos/depositos': typeof AdminGeneralMovimientosDepositosRoute
  '/admin/general/movimientos/impuestos': typeof AdminGeneralMovimientosImpuestosRoute
  '/admin/general/movimientos/pagos-qr': typeof AdminGeneralMovimientosPagosQrRoute
  '/admin/general/movimientos/pagos-tarjeta': typeof AdminGeneralMovimientosPagosTarjetaRoute
  '/admin/general/movimientos/retiros': typeof AdminGeneralMovimientosRetirosRoute
  '/admin/general/usuarios/$legajo': typeof AdminGeneralUsuariosLegajoRoute
  '/admin/general/usuarios/comisiones': typeof AdminGeneralUsuariosComisionesRoute
  '/admin/general/usuarios/cvu': typeof AdminGeneralUsuariosCvuRoute
  '/admin/general/usuarios/juridicas': typeof AdminGeneralUsuariosJuridicasRoute
  '/admin/administracion/registros/': typeof AdminAdministracionRegistrosIndexRoute
  '/admin/administracion/soporte/': typeof AdminAdministracionSoporteIndexRoute
  '/admin/administracion/usuarios/': typeof AdminAdministracionUsuariosIndexRoute
  '/admin/comercios/apis/': typeof AdminComerciosApisIndexRoute
  '/admin/comercios/impuestos/': typeof AdminComerciosImpuestosIndexRoute
  '/admin/comercios/transferencia/': typeof AdminComerciosTransferenciaIndexRoute
  '/admin/general/alertas/': typeof AdminGeneralAlertasIndexRoute
  '/admin/general/movimientos/': typeof AdminGeneralMovimientosIndexRoute
  '/admin/general/usuarios/': typeof AdminGeneralUsuariosIndexRoute
  '/admin/otc/registro/': typeof AdminOtcRegistroIndexRoute
  '/admin/pagos/solicitudes/': typeof AdminPagosSolicitudesIndexRoute
  '/admin/verificacion/clientes/': typeof AdminVerificacionClientesIndexRoute
  '/admin/comercios/impuestos/ingresos-brutos/': typeof AdminComerciosImpuestosIngresosBrutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/comercios'
    | '/admin/configuracion'
    | '/admin/incidentes'
    | '/admin/modulos'
    | '/admin/notificaciones'
    | '/legales/arrepentimiento'
    | '/legales/comisiones'
    | '/legales/privacidad'
    | '/legales/terminos'
    | '/admin/'
    | '/admin/administracion/registros'
    | '/admin/administracion/reportes'
    | '/admin/administracion/soporte'
    | '/admin/administracion/usuarios'
    | '/admin/comercios/apis'
    | '/admin/comercios/impuestos'
    | '/admin/comercios/link-pago'
    | '/admin/comercios/transferencia'
    | '/admin/configuracion/configuraciones'
    | '/admin/configuracion/logins'
    | '/admin/estadisticas/depositos-retiros'
    | '/admin/estadisticas/indicadores'
    | '/admin/general/alertas'
    | '/admin/general/movimientos'
    | '/admin/general/usuarios'
    | '/admin/otc/tasas'
    | '/admin/pagos/aprobacion'
    | '/admin/pagos/comprobantes'
    | '/admin/verificacion/identidad'
    | '/admin/verificacion/listas'
    | '/admin/comercios/'
    | '/admin/configuracion/'
    | '/admin/notificaciones/'
    | '/admin/administracion/registros/actividad'
    | '/admin/administracion/registros/total'
    | '/admin/administracion/soporte/bloqueo'
    | '/admin/administracion/usuarios/roles'
    | '/admin/comercios/apis/endpoints'
    | '/admin/comercios/apis/restricciones'
    | '/admin/comercios/impuestos/debitos-creditos'
    | '/admin/comercios/impuestos/ingresos-brutos'
    | '/admin/comercios/impuestos/usuarios'
    | '/admin/comercios/transferencia/categorias'
    | '/admin/comercios/transferencia/resolvers'
    | '/admin/general/alertas/bloqueos'
    | '/admin/general/alertas/parametros-alertas'
    | '/admin/general/alertas/parametros-bloqueos'
    | '/admin/general/movimientos/cobros-qr'
    | '/admin/general/movimientos/comisiones'
    | '/admin/general/movimientos/depositos'
    | '/admin/general/movimientos/impuestos'
    | '/admin/general/movimientos/pagos-qr'
    | '/admin/general/movimientos/pagos-tarjeta'
    | '/admin/general/movimientos/retiros'
    | '/admin/general/usuarios/$legajo'
    | '/admin/general/usuarios/comisiones'
    | '/admin/general/usuarios/cvu'
    | '/admin/general/usuarios/juridicas'
    | '/admin/administracion/registros/'
    | '/admin/administracion/soporte/'
    | '/admin/administracion/usuarios/'
    | '/admin/comercios/apis/'
    | '/admin/comercios/impuestos/'
    | '/admin/comercios/transferencia/'
    | '/admin/general/alertas/'
    | '/admin/general/movimientos/'
    | '/admin/general/usuarios/'
    | '/admin/otc/registro/'
    | '/admin/pagos/solicitudes/'
    | '/admin/verificacion/clientes/'
    | '/admin/comercios/impuestos/ingresos-brutos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/incidentes'
    | '/admin/modulos'
    | '/legales/arrepentimiento'
    | '/legales/comisiones'
    | '/legales/privacidad'
    | '/legales/terminos'
    | '/admin'
    | '/admin/administracion/reportes'
    | '/admin/comercios/link-pago'
    | '/admin/configuracion/configuraciones'
    | '/admin/configuracion/logins'
    | '/admin/estadisticas/depositos-retiros'
    | '/admin/estadisticas/indicadores'
    | '/admin/otc/tasas'
    | '/admin/pagos/aprobacion'
    | '/admin/pagos/comprobantes'
    | '/admin/verificacion/identidad'
    | '/admin/verificacion/listas'
    | '/admin/comercios'
    | '/admin/configuracion'
    | '/admin/notificaciones'
    | '/admin/administracion/registros/actividad'
    | '/admin/administracion/registros/total'
    | '/admin/administracion/soporte/bloqueo'
    | '/admin/administracion/usuarios/roles'
    | '/admin/comercios/apis/endpoints'
    | '/admin/comercios/apis/restricciones'
    | '/admin/comercios/impuestos/debitos-creditos'
    | '/admin/comercios/impuestos/usuarios'
    | '/admin/comercios/transferencia/categorias'
    | '/admin/comercios/transferencia/resolvers'
    | '/admin/general/alertas/bloqueos'
    | '/admin/general/alertas/parametros-alertas'
    | '/admin/general/alertas/parametros-bloqueos'
    | '/admin/general/movimientos/cobros-qr'
    | '/admin/general/movimientos/comisiones'
    | '/admin/general/movimientos/depositos'
    | '/admin/general/movimientos/impuestos'
    | '/admin/general/movimientos/pagos-qr'
    | '/admin/general/movimientos/pagos-tarjeta'
    | '/admin/general/movimientos/retiros'
    | '/admin/general/usuarios/$legajo'
    | '/admin/general/usuarios/comisiones'
    | '/admin/general/usuarios/cvu'
    | '/admin/general/usuarios/juridicas'
    | '/admin/administracion/registros'
    | '/admin/administracion/soporte'
    | '/admin/administracion/usuarios'
    | '/admin/comercios/apis'
    | '/admin/comercios/impuestos'
    | '/admin/comercios/transferencia'
    | '/admin/general/alertas'
    | '/admin/general/movimientos'
    | '/admin/general/usuarios'
    | '/admin/otc/registro'
    | '/admin/pagos/solicitudes'
    | '/admin/verificacion/clientes'
    | '/admin/comercios/impuestos/ingresos-brutos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/comercios'
    | '/admin/configuracion'
    | '/admin/incidentes'
    | '/admin/modulos'
    | '/admin/notificaciones'
    | '/legales/arrepentimiento'
    | '/legales/comisiones'
    | '/legales/privacidad'
    | '/legales/terminos'
    | '/admin/'
    | '/admin/administracion/registros'
    | '/admin/administracion/reportes'
    | '/admin/administracion/soporte'
    | '/admin/administracion/usuarios'
    | '/admin/comercios/apis'
    | '/admin/comercios/impuestos'
    | '/admin/comercios/link-pago'
    | '/admin/comercios/transferencia'
    | '/admin/configuracion/configuraciones'
    | '/admin/configuracion/logins'
    | '/admin/estadisticas/depositos-retiros'
    | '/admin/estadisticas/indicadores'
    | '/admin/general/alertas'
    | '/admin/general/movimientos'
    | '/admin/general/usuarios'
    | '/admin/otc/tasas'
    | '/admin/pagos/aprobacion'
    | '/admin/pagos/comprobantes'
    | '/admin/verificacion/identidad'
    | '/admin/verificacion/listas'
    | '/admin/comercios/'
    | '/admin/configuracion/'
    | '/admin/notificaciones/'
    | '/admin/administracion/registros/actividad'
    | '/admin/administracion/registros/total'
    | '/admin/administracion/soporte/bloqueo'
    | '/admin/administracion/usuarios/roles'
    | '/admin/comercios/apis/endpoints'
    | '/admin/comercios/apis/restricciones'
    | '/admin/comercios/impuestos/debitos-creditos'
    | '/admin/comercios/impuestos/ingresos-brutos'
    | '/admin/comercios/impuestos/usuarios'
    | '/admin/comercios/transferencia/categorias'
    | '/admin/comercios/transferencia/resolvers'
    | '/admin/general/alertas/bloqueos'
    | '/admin/general/alertas/parametros-alertas'
    | '/admin/general/alertas/parametros-bloqueos'
    | '/admin/general/movimientos/cobros-qr'
    | '/admin/general/movimientos/comisiones'
    | '/admin/general/movimientos/depositos'
    | '/admin/general/movimientos/impuestos'
    | '/admin/general/movimientos/pagos-qr'
    | '/admin/general/movimientos/pagos-tarjeta'
    | '/admin/general/movimientos/retiros'
    | '/admin/general/usuarios/$legajo'
    | '/admin/general/usuarios/comisiones'
    | '/admin/general/usuarios/cvu'
    | '/admin/general/usuarios/juridicas'
    | '/admin/administracion/registros/'
    | '/admin/administracion/soporte/'
    | '/admin/administracion/usuarios/'
    | '/admin/comercios/apis/'
    | '/admin/comercios/impuestos/'
    | '/admin/comercios/transferencia/'
    | '/admin/general/alertas/'
    | '/admin/general/movimientos/'
    | '/admin/general/usuarios/'
    | '/admin/otc/registro/'
    | '/admin/pagos/solicitudes/'
    | '/admin/verificacion/clientes/'
    | '/admin/comercios/impuestos/ingresos-brutos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  LegalesArrepentimientoRoute: typeof LegalesArrepentimientoRoute
  LegalesComisionesRoute: typeof LegalesComisionesRoute
  LegalesPrivacidadRoute: typeof LegalesPrivacidadRoute
  LegalesTerminosRoute: typeof LegalesTerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comercios': {
      id: '/admin/comercios'
      path: '/comercios'
      fullPath: '/admin/comercios'
      preLoaderRoute: typeof AdminComerciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incidentes': {
      id: '/admin/incidentes'
      path: '/incidentes'
      fullPath: '/admin/incidentes'
      preLoaderRoute: typeof AdminIncidentesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modulos': {
      id: '/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AdminModulosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificaciones': {
      id: '/admin/notificaciones'
      path: '/notificaciones'
      fullPath: '/admin/notificaciones'
      preLoaderRoute: typeof AdminNotificacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/legales/arrepentimiento': {
      id: '/legales/arrepentimiento'
      path: '/legales/arrepentimiento'
      fullPath: '/legales/arrepentimiento'
      preLoaderRoute: typeof LegalesArrepentimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legales/comisiones': {
      id: '/legales/comisiones'
      path: '/legales/comisiones'
      fullPath: '/legales/comisiones'
      preLoaderRoute: typeof LegalesComisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legales/privacidad': {
      id: '/legales/privacidad'
      path: '/legales/privacidad'
      fullPath: '/legales/privacidad'
      preLoaderRoute: typeof LegalesPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legales/terminos': {
      id: '/legales/terminos'
      path: '/legales/terminos'
      fullPath: '/legales/terminos'
      preLoaderRoute: typeof LegalesTerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/administracion/registros': {
      id: '/admin/administracion/registros'
      path: '/administracion/registros'
      fullPath: '/admin/administracion/registros'
      preLoaderRoute: typeof AdminAdministracionRegistrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administracion/reportes': {
      id: '/admin/administracion/reportes'
      path: '/administracion/reportes'
      fullPath: '/admin/administracion/reportes'
      preLoaderRoute: typeof AdminAdministracionReportesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administracion/soporte': {
      id: '/admin/administracion/soporte'
      path: '/administracion/soporte'
      fullPath: '/admin/administracion/soporte'
      preLoaderRoute: typeof AdminAdministracionSoporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administracion/usuarios': {
      id: '/admin/administracion/usuarios'
      path: '/administracion/usuarios'
      fullPath: '/admin/administracion/usuarios'
      preLoaderRoute: typeof AdminAdministracionUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comercios/': {
      id: '/admin/comercios/'
      path: '/'
      fullPath: '/admin/comercios/'
      preLoaderRoute: typeof AdminComerciosIndexRouteImport
      parentRoute: typeof AdminComerciosRoute
    }
    '/admin/comercios/apis': {
      id: '/admin/comercios/apis'
      path: '/apis'
      fullPath: '/admin/comercios/apis'
      preLoaderRoute: typeof AdminComerciosApisRouteImport
      parentRoute: typeof AdminComerciosRoute
    }
    '/admin/comercios/impuestos': {
      id: '/admin/comercios/impuestos'
      path: '/impuestos'
      fullPath: '/admin/comercios/impuestos'
      preLoaderRoute: typeof AdminComerciosImpuestosRouteImport
      parentRoute: typeof AdminComerciosRoute
    }
    '/admin/comercios/link-pago': {
      id: '/admin/comercios/link-pago'
      path: '/link-pago'
      fullPath: '/admin/comercios/link-pago'
      preLoaderRoute: typeof AdminComerciosLinkPagoRouteImport
      parentRoute: typeof AdminComerciosRoute
    }
    '/admin/comercios/transferencia': {
      id: '/admin/comercios/transferencia'
      path: '/transferencia'
      fullPath: '/admin/comercios/transferencia'
      preLoaderRoute: typeof AdminComerciosTransferenciaRouteImport
      parentRoute: typeof AdminComerciosRoute
    }
    '/admin/configuracion/': {
      id: '/admin/configuracion/'
      path: '/'
      fullPath: '/admin/configuracion/'
      preLoaderRoute: typeof AdminConfiguracionIndexRouteImport
      parentRoute: typeof AdminConfiguracionRoute
    }
    '/admin/configuracion/configuraciones': {
      id: '/admin/configuracion/configuraciones'
      path: '/configuraciones'
      fullPath: '/admin/configuracion/configuraciones'
      preLoaderRoute: typeof AdminConfiguracionConfiguracionesRouteImport
      parentRoute: typeof AdminConfiguracionRoute
    }
    '/admin/configuracion/logins': {
      id: '/admin/configuracion/logins'
      path: '/logins'
      fullPath: '/admin/configuracion/logins'
      preLoaderRoute: typeof AdminConfiguracionLoginsRouteImport
      parentRoute: typeof AdminConfiguracionRoute
    }
    '/admin/estadisticas/depositos-retiros': {
      id: '/admin/estadisticas/depositos-retiros'
      path: '/estadisticas/depositos-retiros'
      fullPath: '/admin/estadisticas/depositos-retiros'
      preLoaderRoute: typeof AdminEstadisticasDepositosRetirosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estadisticas/indicadores': {
      id: '/admin/estadisticas/indicadores'
      path: '/estadisticas/indicadores'
      fullPath: '/admin/estadisticas/indicadores'
      preLoaderRoute: typeof AdminEstadisticasIndicadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/general/alertas': {
      id: '/admin/general/alertas'
      path: '/general/alertas'
      fullPath: '/admin/general/alertas'
      preLoaderRoute: typeof AdminGeneralAlertasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/general/movimientos': {
      id: '/admin/general/movimientos'
      path: '/general/movimientos'
      fullPath: '/admin/general/movimientos'
      preLoaderRoute: typeof AdminGeneralMovimientosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/general/usuarios': {
      id: '/admin/general/usuarios'
      path: '/general/usuarios'
      fullPath: '/admin/general/usuarios'
      preLoaderRoute: typeof AdminGeneralUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificaciones/': {
      id: '/admin/notificaciones/'
      path: '/'
      fullPath: '/admin/notificaciones/'
      preLoaderRoute: typeof AdminNotificacionesIndexRouteImport
      parentRoute: typeof AdminNotificacionesRoute
    }
    '/admin/otc/tasas': {
      id: '/admin/otc/tasas'
      path: '/otc/tasas'
      fullPath: '/admin/otc/tasas'
      preLoaderRoute: typeof AdminOtcTasasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagos/aprobacion': {
      id: '/admin/pagos/aprobacion'
      path: '/pagos/aprobacion'
      fullPath: '/admin/pagos/aprobacion'
      preLoaderRoute: typeof AdminPagosAprobacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagos/comprobantes': {
      id: '/admin/pagos/comprobantes'
      path: '/pagos/comprobantes'
      fullPath: '/admin/pagos/comprobantes'
      preLoaderRoute: typeof AdminPagosComprobantesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verificacion/identidad': {
      id: '/admin/verificacion/identidad'
      path: '/verificacion/identidad'
      fullPath: '/admin/verificacion/identidad'
      preLoaderRoute: typeof AdminVerificacionIdentidadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verificacion/listas': {
      id: '/admin/verificacion/listas'
      path: '/verificacion/listas'
      fullPath: '/admin/verificacion/listas'
      preLoaderRoute: typeof AdminVerificacionListasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administracion/registros/': {
      id: '/admin/administracion/registros/'
      path: '/'
      fullPath: '/admin/administracion/registros/'
      preLoaderRoute: typeof AdminAdministracionRegistrosIndexRouteImport
      parentRoute: typeof AdminAdministracionRegistrosRoute
    }
    '/admin/administracion/registros/actividad': {
      id: '/admin/administracion/registros/actividad'
      path: '/actividad'
      fullPath: '/admin/administracion/registros/actividad'
      preLoaderRoute: typeof AdminAdministracionRegistrosActividadRouteImport
      parentRoute: typeof AdminAdministracionRegistrosRoute
    }
    '/admin/administracion/registros/total': {
      id: '/admin/administracion/registros/total'
      path: '/total'
      fullPath: '/admin/administracion/registros/total'
      preLoaderRoute: typeof AdminAdministracionRegistrosTotalRouteImport
      parentRoute: typeof AdminAdministracionRegistrosRoute
    }
    '/admin/administracion/soporte/': {
      id: '/admin/administracion/soporte/'
      path: '/'
      fullPath: '/admin/administracion/soporte/'
      preLoaderRoute: typeof AdminAdministracionSoporteIndexRouteImport
      parentRoute: typeof AdminAdministracionSoporteRoute
    }
    '/admin/administracion/soporte/bloqueo': {
      id: '/admin/administracion/soporte/bloqueo'
      path: '/bloqueo'
      fullPath: '/admin/administracion/soporte/bloqueo'
      preLoaderRoute: typeof AdminAdministracionSoporteBloqueoRouteImport
      parentRoute: typeof AdminAdministracionSoporteRoute
    }
    '/admin/administracion/usuarios/': {
      id: '/admin/administracion/usuarios/'
      path: '/'
      fullPath: '/admin/administracion/usuarios/'
      preLoaderRoute: typeof AdminAdministracionUsuariosIndexRouteImport
      parentRoute: typeof AdminAdministracionUsuariosRoute
    }
    '/admin/administracion/usuarios/roles': {
      id: '/admin/administracion/usuarios/roles'
      path: '/roles'
      fullPath: '/admin/administracion/usuarios/roles'
      preLoaderRoute: typeof AdminAdministracionUsuariosRolesRouteImport
      parentRoute: typeof AdminAdministracionUsuariosRoute
    }
    '/admin/comercios/apis/': {
      id: '/admin/comercios/apis/'
      path: '/'
      fullPath: '/admin/comercios/apis/'
      preLoaderRoute: typeof AdminComerciosApisIndexRouteImport
      parentRoute: typeof AdminComerciosApisRoute
    }
    '/admin/comercios/apis/endpoints': {
      id: '/admin/comercios/apis/endpoints'
      path: '/endpoints'
      fullPath: '/admin/comercios/apis/endpoints'
      preLoaderRoute: typeof AdminComerciosApisEndpointsRouteImport
      parentRoute: typeof AdminComerciosApisRoute
    }
    '/admin/comercios/apis/restricciones': {
      id: '/admin/comercios/apis/restricciones'
      path: '/restricciones'
      fullPath: '/admin/comercios/apis/restricciones'
      preLoaderRoute: typeof AdminComerciosApisRestriccionesRouteImport
      parentRoute: typeof AdminComerciosApisRoute
    }
    '/admin/comercios/impuestos/': {
      id: '/admin/comercios/impuestos/'
      path: '/'
      fullPath: '/admin/comercios/impuestos/'
      preLoaderRoute: typeof AdminComerciosImpuestosIndexRouteImport
      parentRoute: typeof AdminComerciosImpuestosRoute
    }
    '/admin/comercios/impuestos/debitos-creditos': {
      id: '/admin/comercios/impuestos/debitos-creditos'
      path: '/debitos-creditos'
      fullPath: '/admin/comercios/impuestos/debitos-creditos'
      preLoaderRoute: typeof AdminComerciosImpuestosDebitosCreditosRouteImport
      parentRoute: typeof AdminComerciosImpuestosRoute
    }
    '/admin/comercios/impuestos/ingresos-brutos': {
      id: '/admin/comercios/impuestos/ingresos-brutos'
      path: '/ingresos-brutos'
      fullPath: '/admin/comercios/impuestos/ingresos-brutos'
      preLoaderRoute: typeof AdminComerciosImpuestosIngresosBrutosRouteImport
      parentRoute: typeof AdminComerciosImpuestosRoute
    }
    '/admin/comercios/impuestos/usuarios': {
      id: '/admin/comercios/impuestos/usuarios'
      path: '/usuarios'
      fullPath: '/admin/comercios/impuestos/usuarios'
      preLoaderRoute: typeof AdminComerciosImpuestosUsuariosRouteImport
      parentRoute: typeof AdminComerciosImpuestosRoute
    }
    '/admin/comercios/transferencia/': {
      id: '/admin/comercios/transferencia/'
      path: '/'
      fullPath: '/admin/comercios/transferencia/'
      preLoaderRoute: typeof AdminComerciosTransferenciaIndexRouteImport
      parentRoute: typeof AdminComerciosTransferenciaRoute
    }
    '/admin/comercios/transferencia/categorias': {
      id: '/admin/comercios/transferencia/categorias'
      path: '/categorias'
      fullPath: '/admin/comercios/transferencia/categorias'
      preLoaderRoute: typeof AdminComerciosTransferenciaCategoriasRouteImport
      parentRoute: typeof AdminComerciosTransferenciaRoute
    }
    '/admin/comercios/transferencia/resolvers': {
      id: '/admin/comercios/transferencia/resolvers'
      path: '/resolvers'
      fullPath: '/admin/comercios/transferencia/resolvers'
      preLoaderRoute: typeof AdminComerciosTransferenciaResolversRouteImport
      parentRoute: typeof AdminComerciosTransferenciaRoute
    }
    '/admin/general/alertas/': {
      id: '/admin/general/alertas/'
      path: '/'
      fullPath: '/admin/general/alertas/'
      preLoaderRoute: typeof AdminGeneralAlertasIndexRouteImport
      parentRoute: typeof AdminGeneralAlertasRoute
    }
    '/admin/general/alertas/bloqueos': {
      id: '/admin/general/alertas/bloqueos'
      path: '/bloqueos'
      fullPath: '/admin/general/alertas/bloqueos'
      preLoaderRoute: typeof AdminGeneralAlertasBloqueosRouteImport
      parentRoute: typeof AdminGeneralAlertasRoute
    }
    '/admin/general/alertas/parametros-alertas': {
      id: '/admin/general/alertas/parametros-alertas'
      path: '/parametros-alertas'
      fullPath: '/admin/general/alertas/parametros-alertas'
      preLoaderRoute: typeof AdminGeneralAlertasParametrosAlertasRouteImport
      parentRoute: typeof AdminGeneralAlertasRoute
    }
    '/admin/general/alertas/parametros-bloqueos': {
      id: '/admin/general/alertas/parametros-bloqueos'
      path: '/parametros-bloqueos'
      fullPath: '/admin/general/alertas/parametros-bloqueos'
      preLoaderRoute: typeof AdminGeneralAlertasParametrosBloqueosRouteImport
      parentRoute: typeof AdminGeneralAlertasRoute
    }
    '/admin/general/movimientos/': {
      id: '/admin/general/movimientos/'
      path: '/'
      fullPath: '/admin/general/movimientos/'
      preLoaderRoute: typeof AdminGeneralMovimientosIndexRouteImport
      parentRoute: typeof AdminGeneralMovimientosRoute
    }
    '/admin/general/movimientos/cobros-qr': {
      id: '/admin/general/movimientos/cobros-qr'
      path: '/cobros-qr'
      fullPath: '/admin/general/movimientos/cobros-qr'
      preLoaderRoute: typeof AdminGeneralMovimientosCobrosQrRouteImport
      parentRoute: typeof AdminGeneralMovimientosRoute
    }
    '/admin/general/movimientos/comisiones': {
      id: '/admin/general/movimientos/comisiones'
      path: '/comisiones'
      fullPath: '/admin/general/movimientos/comisiones'
      preLoaderRoute: typeof AdminGeneralMovimientosComisionesRouteImport
      parentRoute: typeof AdminGeneralMovimientosRoute
    }
    '/admin/general/movimientos/depositos': {
      id: '/admin/general/movimientos/depositos'
      path: '/depositos'
      fullPath: '/admin/general/movimientos/depositos'
      preLoaderRoute: typeof AdminGeneralMovimientosDepositosRouteImport
      parentRoute: typeof AdminGeneralMovimientosRoute
    }
    '/admin/general/movimientos/impuestos': {
      id: '/admin/general/movimientos/impuestos'
      path: '/impuestos'
      fullPath: '/admin/general/movimientos/impuestos'
      preLoaderRoute: typeof AdminGeneralMovimientosImpuestosRouteImport
      parentRoute: typeof AdminGeneralMovimientosRoute
    }
    '/admin/general/movimientos/pagos-qr': {
      id: '/admin/general/movimientos/pagos-qr'
      path: '/pagos-qr'
      fullPath: '/admin/general/movimientos/pagos-qr'
      preLoaderRoute: typeof AdminGeneralMovimientosPagosQrRouteImport
      parentRoute: typeof AdminGeneralMovimientosRoute
    }
    '/admin/general/movimientos/pagos-tarjeta': {
      id: '/admin/general/movimientos/pagos-tarjeta'
      path: '/pagos-tarjeta'
      fullPath: '/admin/general/movimientos/pagos-tarjeta'
      preLoaderRoute: typeof AdminGeneralMovimientosPagosTarjetaRouteImport
      parentRoute: typeof AdminGeneralMovimientosRoute
    }
    '/admin/general/movimientos/retiros': {
      id: '/admin/general/movimientos/retiros'
      path: '/retiros'
      fullPath: '/admin/general/movimientos/retiros'
      preLoaderRoute: typeof AdminGeneralMovimientosRetirosRouteImport
      parentRoute: typeof AdminGeneralMovimientosRoute
    }
    '/admin/general/usuarios/': {
      id: '/admin/general/usuarios/'
      path: '/'
      fullPath: '/admin/general/usuarios/'
      preLoaderRoute: typeof AdminGeneralUsuariosIndexRouteImport
      parentRoute: typeof AdminGeneralUsuariosRoute
    }
    '/admin/general/usuarios/$legajo': {
      id: '/admin/general/usuarios/$legajo'
      path: '/$legajo'
      fullPath: '/admin/general/usuarios/$legajo'
      preLoaderRoute: typeof AdminGeneralUsuariosLegajoRouteImport
      parentRoute: typeof AdminGeneralUsuariosRoute
    }
    '/admin/general/usuarios/comisiones': {
      id: '/admin/general/usuarios/comisiones'
      path: '/comisiones'
      fullPath: '/admin/general/usuarios/comisiones'
      preLoaderRoute: typeof AdminGeneralUsuariosComisionesRouteImport
      parentRoute: typeof AdminGeneralUsuariosRoute
    }
    '/admin/general/usuarios/cvu': {
      id: '/admin/general/usuarios/cvu'
      path: '/cvu'
      fullPath: '/admin/general/usuarios/cvu'
      preLoaderRoute: typeof AdminGeneralUsuariosCvuRouteImport
      parentRoute: typeof AdminGeneralUsuariosRoute
    }
    '/admin/general/usuarios/juridicas': {
      id: '/admin/general/usuarios/juridicas'
      path: '/juridicas'
      fullPath: '/admin/general/usuarios/juridicas'
      preLoaderRoute: typeof AdminGeneralUsuariosJuridicasRouteImport
      parentRoute: typeof AdminGeneralUsuariosRoute
    }
    '/admin/otc/registro/': {
      id: '/admin/otc/registro/'
      path: '/otc/registro'
      fullPath: '/admin/otc/registro/'
      preLoaderRoute: typeof AdminOtcRegistroIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagos/solicitudes/': {
      id: '/admin/pagos/solicitudes/'
      path: '/pagos/solicitudes'
      fullPath: '/admin/pagos/solicitudes/'
      preLoaderRoute: typeof AdminPagosSolicitudesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verificacion/clientes/': {
      id: '/admin/verificacion/clientes/'
      path: '/verificacion/clientes'
      fullPath: '/admin/verificacion/clientes/'
      preLoaderRoute: typeof AdminVerificacionClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comercios/impuestos/ingresos-brutos/': {
      id: '/admin/comercios/impuestos/ingresos-brutos/'
      path: '/'
      fullPath: '/admin/comercios/impuestos/ingresos-brutos/'
      preLoaderRoute: typeof AdminComerciosImpuestosIngresosBrutosIndexRouteImport
      parentRoute: typeof AdminComerciosImpuestosIngresosBrutosRoute
    }
  }
}

interface AdminComerciosApisRouteChildren {
  AdminComerciosApisEndpointsRoute: typeof AdminComerciosApisEndpointsRoute
  AdminComerciosApisRestriccionesRoute: typeof AdminComerciosApisRestriccionesRoute
  AdminComerciosApisIndexRoute: typeof AdminComerciosApisIndexRoute
}

const AdminComerciosApisRouteChildren: AdminComerciosApisRouteChildren = {
  AdminComerciosApisEndpointsRoute: AdminComerciosApisEndpointsRoute,
  AdminComerciosApisRestriccionesRoute: AdminComerciosApisRestriccionesRoute,
  AdminComerciosApisIndexRoute: AdminComerciosApisIndexRoute,
}

const AdminComerciosApisRouteWithChildren =
  AdminComerciosApisRoute._addFileChildren(AdminComerciosApisRouteChildren)

interface AdminComerciosImpuestosIngresosBrutosRouteChildren {
  AdminComerciosImpuestosIngresosBrutosIndexRoute: typeof AdminComerciosImpuestosIngresosBrutosIndexRoute
}

const AdminComerciosImpuestosIngresosBrutosRouteChildren: AdminComerciosImpuestosIngresosBrutosRouteChildren =
  {
    AdminComerciosImpuestosIngresosBrutosIndexRoute:
      AdminComerciosImpuestosIngresosBrutosIndexRoute,
  }

const AdminComerciosImpuestosIngresosBrutosRouteWithChildren =
  AdminComerciosImpuestosIngresosBrutosRoute._addFileChildren(
    AdminComerciosImpuestosIngresosBrutosRouteChildren,
  )

interface AdminComerciosImpuestosRouteChildren {
  AdminComerciosImpuestosDebitosCreditosRoute: typeof AdminComerciosImpuestosDebitosCreditosRoute
  AdminComerciosImpuestosIngresosBrutosRoute: typeof AdminComerciosImpuestosIngresosBrutosRouteWithChildren
  AdminComerciosImpuestosUsuariosRoute: typeof AdminComerciosImpuestosUsuariosRoute
  AdminComerciosImpuestosIndexRoute: typeof AdminComerciosImpuestosIndexRoute
}

const AdminComerciosImpuestosRouteChildren: AdminComerciosImpuestosRouteChildren =
  {
    AdminComerciosImpuestosDebitosCreditosRoute:
      AdminComerciosImpuestosDebitosCreditosRoute,
    AdminComerciosImpuestosIngresosBrutosRoute:
      AdminComerciosImpuestosIngresosBrutosRouteWithChildren,
    AdminComerciosImpuestosUsuariosRoute: AdminComerciosImpuestosUsuariosRoute,
    AdminComerciosImpuestosIndexRoute: AdminComerciosImpuestosIndexRoute,
  }

const AdminComerciosImpuestosRouteWithChildren =
  AdminComerciosImpuestosRoute._addFileChildren(
    AdminComerciosImpuestosRouteChildren,
  )

interface AdminComerciosTransferenciaRouteChildren {
  AdminComerciosTransferenciaCategoriasRoute: typeof AdminComerciosTransferenciaCategoriasRoute
  AdminComerciosTransferenciaResolversRoute: typeof AdminComerciosTransferenciaResolversRoute
  AdminComerciosTransferenciaIndexRoute: typeof AdminComerciosTransferenciaIndexRoute
}

const AdminComerciosTransferenciaRouteChildren: AdminComerciosTransferenciaRouteChildren =
  {
    AdminComerciosTransferenciaCategoriasRoute:
      AdminComerciosTransferenciaCategoriasRoute,
    AdminComerciosTransferenciaResolversRoute:
      AdminComerciosTransferenciaResolversRoute,
    AdminComerciosTransferenciaIndexRoute:
      AdminComerciosTransferenciaIndexRoute,
  }

const AdminComerciosTransferenciaRouteWithChildren =
  AdminComerciosTransferenciaRoute._addFileChildren(
    AdminComerciosTransferenciaRouteChildren,
  )

interface AdminComerciosRouteChildren {
  AdminComerciosApisRoute: typeof AdminComerciosApisRouteWithChildren
  AdminComerciosImpuestosRoute: typeof AdminComerciosImpuestosRouteWithChildren
  AdminComerciosLinkPagoRoute: typeof AdminComerciosLinkPagoRoute
  AdminComerciosTransferenciaRoute: typeof AdminComerciosTransferenciaRouteWithChildren
  AdminComerciosIndexRoute: typeof AdminComerciosIndexRoute
}

const AdminComerciosRouteChildren: AdminComerciosRouteChildren = {
  AdminComerciosApisRoute: AdminComerciosApisRouteWithChildren,
  AdminComerciosImpuestosRoute: AdminComerciosImpuestosRouteWithChildren,
  AdminComerciosLinkPagoRoute: AdminComerciosLinkPagoRoute,
  AdminComerciosTransferenciaRoute:
    AdminComerciosTransferenciaRouteWithChildren,
  AdminComerciosIndexRoute: AdminComerciosIndexRoute,
}

const AdminComerciosRouteWithChildren = AdminComerciosRoute._addFileChildren(
  AdminComerciosRouteChildren,
)

interface AdminConfiguracionRouteChildren {
  AdminConfiguracionConfiguracionesRoute: typeof AdminConfiguracionConfiguracionesRoute
  AdminConfiguracionLoginsRoute: typeof AdminConfiguracionLoginsRoute
  AdminConfiguracionIndexRoute: typeof AdminConfiguracionIndexRoute
}

const AdminConfiguracionRouteChildren: AdminConfiguracionRouteChildren = {
  AdminConfiguracionConfiguracionesRoute:
    AdminConfiguracionConfiguracionesRoute,
  AdminConfiguracionLoginsRoute: AdminConfiguracionLoginsRoute,
  AdminConfiguracionIndexRoute: AdminConfiguracionIndexRoute,
}

const AdminConfiguracionRouteWithChildren =
  AdminConfiguracionRoute._addFileChildren(AdminConfiguracionRouteChildren)

interface AdminNotificacionesRouteChildren {
  AdminNotificacionesIndexRoute: typeof AdminNotificacionesIndexRoute
}

const AdminNotificacionesRouteChildren: AdminNotificacionesRouteChildren = {
  AdminNotificacionesIndexRoute: AdminNotificacionesIndexRoute,
}

const AdminNotificacionesRouteWithChildren =
  AdminNotificacionesRoute._addFileChildren(AdminNotificacionesRouteChildren)

interface AdminAdministracionRegistrosRouteChildren {
  AdminAdministracionRegistrosActividadRoute: typeof AdminAdministracionRegistrosActividadRoute
  AdminAdministracionRegistrosTotalRoute: typeof AdminAdministracionRegistrosTotalRoute
  AdminAdministracionRegistrosIndexRoute: typeof AdminAdministracionRegistrosIndexRoute
}

const AdminAdministracionRegistrosRouteChildren: AdminAdministracionRegistrosRouteChildren =
  {
    AdminAdministracionRegistrosActividadRoute:
      AdminAdministracionRegistrosActividadRoute,
    AdminAdministracionRegistrosTotalRoute:
      AdminAdministracionRegistrosTotalRoute,
    AdminAdministracionRegistrosIndexRoute:
      AdminAdministracionRegistrosIndexRoute,
  }

const AdminAdministracionRegistrosRouteWithChildren =
  AdminAdministracionRegistrosRoute._addFileChildren(
    AdminAdministracionRegistrosRouteChildren,
  )

interface AdminAdministracionSoporteRouteChildren {
  AdminAdministracionSoporteBloqueoRoute: typeof AdminAdministracionSoporteBloqueoRoute
  AdminAdministracionSoporteIndexRoute: typeof AdminAdministracionSoporteIndexRoute
}

const AdminAdministracionSoporteRouteChildren: AdminAdministracionSoporteRouteChildren =
  {
    AdminAdministracionSoporteBloqueoRoute:
      AdminAdministracionSoporteBloqueoRoute,
    AdminAdministracionSoporteIndexRoute: AdminAdministracionSoporteIndexRoute,
  }

const AdminAdministracionSoporteRouteWithChildren =
  AdminAdministracionSoporteRoute._addFileChildren(
    AdminAdministracionSoporteRouteChildren,
  )

interface AdminAdministracionUsuariosRouteChildren {
  AdminAdministracionUsuariosRolesRoute: typeof AdminAdministracionUsuariosRolesRoute
  AdminAdministracionUsuariosIndexRoute: typeof AdminAdministracionUsuariosIndexRoute
}

const AdminAdministracionUsuariosRouteChildren: AdminAdministracionUsuariosRouteChildren =
  {
    AdminAdministracionUsuariosRolesRoute:
      AdminAdministracionUsuariosRolesRoute,
    AdminAdministracionUsuariosIndexRoute:
      AdminAdministracionUsuariosIndexRoute,
  }

const AdminAdministracionUsuariosRouteWithChildren =
  AdminAdministracionUsuariosRoute._addFileChildren(
    AdminAdministracionUsuariosRouteChildren,
  )

interface AdminGeneralAlertasRouteChildren {
  AdminGeneralAlertasBloqueosRoute: typeof AdminGeneralAlertasBloqueosRoute
  AdminGeneralAlertasParametrosAlertasRoute: typeof AdminGeneralAlertasParametrosAlertasRoute
  AdminGeneralAlertasParametrosBloqueosRoute: typeof AdminGeneralAlertasParametrosBloqueosRoute
  AdminGeneralAlertasIndexRoute: typeof AdminGeneralAlertasIndexRoute
}

const AdminGeneralAlertasRouteChildren: AdminGeneralAlertasRouteChildren = {
  AdminGeneralAlertasBloqueosRoute: AdminGeneralAlertasBloqueosRoute,
  AdminGeneralAlertasParametrosAlertasRoute:
    AdminGeneralAlertasParametrosAlertasRoute,
  AdminGeneralAlertasParametrosBloqueosRoute:
    AdminGeneralAlertasParametrosBloqueosRoute,
  AdminGeneralAlertasIndexRoute: AdminGeneralAlertasIndexRoute,
}

const AdminGeneralAlertasRouteWithChildren =
  AdminGeneralAlertasRoute._addFileChildren(AdminGeneralAlertasRouteChildren)

interface AdminGeneralMovimientosRouteChildren {
  AdminGeneralMovimientosCobrosQrRoute: typeof AdminGeneralMovimientosCobrosQrRoute
  AdminGeneralMovimientosComisionesRoute: typeof AdminGeneralMovimientosComisionesRoute
  AdminGeneralMovimientosDepositosRoute: typeof AdminGeneralMovimientosDepositosRoute
  AdminGeneralMovimientosImpuestosRoute: typeof AdminGeneralMovimientosImpuestosRoute
  AdminGeneralMovimientosPagosQrRoute: typeof AdminGeneralMovimientosPagosQrRoute
  AdminGeneralMovimientosPagosTarjetaRoute: typeof AdminGeneralMovimientosPagosTarjetaRoute
  AdminGeneralMovimientosRetirosRoute: typeof AdminGeneralMovimientosRetirosRoute
  AdminGeneralMovimientosIndexRoute: typeof AdminGeneralMovimientosIndexRoute
}

const AdminGeneralMovimientosRouteChildren: AdminGeneralMovimientosRouteChildren =
  {
    AdminGeneralMovimientosCobrosQrRoute: AdminGeneralMovimientosCobrosQrRoute,
    AdminGeneralMovimientosComisionesRoute:
      AdminGeneralMovimientosComisionesRoute,
    AdminGeneralMovimientosDepositosRoute:
      AdminGeneralMovimientosDepositosRoute,
    AdminGeneralMovimientosImpuestosRoute:
      AdminGeneralMovimientosImpuestosRoute,
    AdminGeneralMovimientosPagosQrRoute: AdminGeneralMovimientosPagosQrRoute,
    AdminGeneralMovimientosPagosTarjetaRoute:
      AdminGeneralMovimientosPagosTarjetaRoute,
    AdminGeneralMovimientosRetirosRoute: AdminGeneralMovimientosRetirosRoute,
    AdminGeneralMovimientosIndexRoute: AdminGeneralMovimientosIndexRoute,
  }

const AdminGeneralMovimientosRouteWithChildren =
  AdminGeneralMovimientosRoute._addFileChildren(
    AdminGeneralMovimientosRouteChildren,
  )

interface AdminGeneralUsuariosRouteChildren {
  AdminGeneralUsuariosLegajoRoute: typeof AdminGeneralUsuariosLegajoRoute
  AdminGeneralUsuariosComisionesRoute: typeof AdminGeneralUsuariosComisionesRoute
  AdminGeneralUsuariosCvuRoute: typeof AdminGeneralUsuariosCvuRoute
  AdminGeneralUsuariosJuridicasRoute: typeof AdminGeneralUsuariosJuridicasRoute
  AdminGeneralUsuariosIndexRoute: typeof AdminGeneralUsuariosIndexRoute
}

const AdminGeneralUsuariosRouteChildren: AdminGeneralUsuariosRouteChildren = {
  AdminGeneralUsuariosLegajoRoute: AdminGeneralUsuariosLegajoRoute,
  AdminGeneralUsuariosComisionesRoute: AdminGeneralUsuariosComisionesRoute,
  AdminGeneralUsuariosCvuRoute: AdminGeneralUsuariosCvuRoute,
  AdminGeneralUsuariosJuridicasRoute: AdminGeneralUsuariosJuridicasRoute,
  AdminGeneralUsuariosIndexRoute: AdminGeneralUsuariosIndexRoute,
}

const AdminGeneralUsuariosRouteWithChildren =
  AdminGeneralUsuariosRoute._addFileChildren(AdminGeneralUsuariosRouteChildren)

interface AdminRouteChildren {
  AdminComerciosRoute: typeof AdminComerciosRouteWithChildren
  AdminConfiguracionRoute: typeof AdminConfiguracionRouteWithChildren
  AdminIncidentesRoute: typeof AdminIncidentesRoute
  AdminModulosRoute: typeof AdminModulosRoute
  AdminNotificacionesRoute: typeof AdminNotificacionesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdministracionRegistrosRoute: typeof AdminAdministracionRegistrosRouteWithChildren
  AdminAdministracionReportesRoute: typeof AdminAdministracionReportesRoute
  AdminAdministracionSoporteRoute: typeof AdminAdministracionSoporteRouteWithChildren
  AdminAdministracionUsuariosRoute: typeof AdminAdministracionUsuariosRouteWithChildren
  AdminEstadisticasDepositosRetirosRoute: typeof AdminEstadisticasDepositosRetirosRoute
  AdminEstadisticasIndicadoresRoute: typeof AdminEstadisticasIndicadoresRoute
  AdminGeneralAlertasRoute: typeof AdminGeneralAlertasRouteWithChildren
  AdminGeneralMovimientosRoute: typeof AdminGeneralMovimientosRouteWithChildren
  AdminGeneralUsuariosRoute: typeof AdminGeneralUsuariosRouteWithChildren
  AdminOtcTasasRoute: typeof AdminOtcTasasRoute
  AdminPagosAprobacionRoute: typeof AdminPagosAprobacionRoute
  AdminPagosComprobantesRoute: typeof AdminPagosComprobantesRoute
  AdminVerificacionIdentidadRoute: typeof AdminVerificacionIdentidadRoute
  AdminVerificacionListasRoute: typeof AdminVerificacionListasRoute
  AdminOtcRegistroIndexRoute: typeof AdminOtcRegistroIndexRoute
  AdminPagosSolicitudesIndexRoute: typeof AdminPagosSolicitudesIndexRoute
  AdminVerificacionClientesIndexRoute: typeof AdminVerificacionClientesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminComerciosRoute: AdminComerciosRouteWithChildren,
  AdminConfiguracionRoute: AdminConfiguracionRouteWithChildren,
  AdminIncidentesRoute: AdminIncidentesRoute,
  AdminModulosRoute: AdminModulosRoute,
  AdminNotificacionesRoute: AdminNotificacionesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminAdministracionRegistrosRoute:
    AdminAdministracionRegistrosRouteWithChildren,
  AdminAdministracionReportesRoute: AdminAdministracionReportesRoute,
  AdminAdministracionSoporteRoute: AdminAdministracionSoporteRouteWithChildren,
  AdminAdministracionUsuariosRoute:
    AdminAdministracionUsuariosRouteWithChildren,
  AdminEstadisticasDepositosRetirosRoute:
    AdminEstadisticasDepositosRetirosRoute,
  AdminEstadisticasIndicadoresRoute: AdminEstadisticasIndicadoresRoute,
  AdminGeneralAlertasRoute: AdminGeneralAlertasRouteWithChildren,
  AdminGeneralMovimientosRoute: AdminGeneralMovimientosRouteWithChildren,
  AdminGeneralUsuariosRoute: AdminGeneralUsuariosRouteWithChildren,
  AdminOtcTasasRoute: AdminOtcTasasRoute,
  AdminPagosAprobacionRoute: AdminPagosAprobacionRoute,
  AdminPagosComprobantesRoute: AdminPagosComprobantesRoute,
  AdminVerificacionIdentidadRoute: AdminVerificacionIdentidadRoute,
  AdminVerificacionListasRoute: AdminVerificacionListasRoute,
  AdminOtcRegistroIndexRoute: AdminOtcRegistroIndexRoute,
  AdminPagosSolicitudesIndexRoute: AdminPagosSolicitudesIndexRoute,
  AdminVerificacionClientesIndexRoute: AdminVerificacionClientesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  LegalesArrepentimientoRoute: LegalesArrepentimientoRoute,
  LegalesComisionesRoute: LegalesComisionesRoute,
  LegalesPrivacidadRoute: LegalesPrivacidadRoute,
  LegalesTerminosRoute: LegalesTerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
